### ISSUE TITLE
Display (and parse) readme

### ISSUE THREAD

**Issue by JakeWharton** [dennisreimann/ioctocat#10]
It would be nice if the repository overview displayed and parsed the various README formats under the general information. Even just plain text would be nice as a starter.

**Comment by dennisreimann** [comment]
We'd need a way to discover the URL of the readme... trying to search for one of the possible formats is ... hmm...

**Comment by JakeWharton** [comment]
Retrieve a list of files in master's root folder
    tree/show/dbloete/ioctocat/master
or
    blob/show/dbloete/ioctocat/master

Match them against
    ^README(?:.([a-zA-Z]+))?$

If there is more than one match, use the first one where the \1 group matches.

If the extension (remember to lowercase) is "png" display it as an image, otherwise display monospaced text. There doesn't seem to be any existing Objective-C implementations of rdoc, markdown, or textile.

**Comment by bry4n** [comment]
See [Object API](http://develop.github.com/p/object.html) -- You could use this for "View on Github" instead of viewing the actual web content.

So, see the Object API's Blob and you can use it to fetch README.
