### ISSUE TITLE
lastReadingDate is off

### ISSUE THREAD

**Issue by weakfl** [dennisreimann/ioctocat#102]
lastReadingDate seems to be off by two hours, but maybe the amount depends on the timezone you're in.

the result is, that all messages which are less than 2 hours old will be displayed as new, even after refreshing the feed. pretty annoying...

**Comment by koraktor** [comment]
@technoweenie posted on [Convore](https://convore.com/github/github-event-json-feed-problems/) that he updated the JSON feeds. Maybe related, because I noted this problem a few days ago for the first time, too. iOctocat itself hasn't been updated in that time.

**Comment by cvx** [comment]
It seems that update time is in UTC despite of "-07:00" postfix.

**Comment by dennisreimann** [comment]
I guess we'll have to wait till this is fixed by GitHub.

**Comment by aharren** [comment]
It's fixed by GitHub. See issue #103.

**Comment by koraktor** [comment]
Fixed, but iOctocat is always crashing now. :(

**Comment by weakfl** [comment]
Nice, thx. But I'm on ios 5 now and unfortunately ioctocat doesn't work anymore. Got it to compile with libz.1.2.5, but it crashes parsing the feed. Probably just something minor, but I don't really have time to take a closer look atm.

**Comment by aharren** [comment]
A fix for the date parsing is in the pull request #103

**Comment by dennisreimann** [comment]
Arne, thank you for taking care of that!
