### ISSUE TITLE
iOS 5 Beta - Won't build

### ISSUE THREAD

**Issue by klaustopher** [dennisreimann/ioctocat#107]
When trying to compile the software for iOS 5, XCode 4.2 throws an error:

```
 ld: library not found for -lz.1.2.3
```

They bundled a new version ob libz.dylib in SDK 5, just go to Project Settings -> Build Phases -> Link Binary with libraries, remove libz-1.2.3.dylib and add libz-1.2.5.dylib

Cannot test this in XCode 4 with an older version of the SDK, but I hope this will help when you are moving on to iOS 5

PS: Thanks for this great piece of software

**Comment by iamhabitat** [comment]
This fixed an issue i was having.  Thanks very much.
