### ISSUE TITLE
iPad split view

### ISSUE THREAD

**Issue by primalmotion** [dennisreimann/ioctocat#110]
I just tried the iPad version of this great project.
Is there any chance to split the screen, to have for example at the left the feed/repo/etc, and at the right the contextual information about the selected item ?

**Comment by dennisreimann** [comment]
Yes, this is planned and will be implemented once the current app is approved by Apple.

**Comment by primalmotion** [comment]
just great :) thanks

**Comment by dennisreimann** [comment]
Progress will be tracked in this pull request: #176
