### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by pfig** [dennisreimann/ioctocat#111]
The latest version in the App Store always crashes on startup, either on authentication or immediately after when it's refreshing the content.

IPhone 4 running latest 4.x iOS.

**Comment by dennisreimann** [comment]
Hi, I'm very sorry for that. This is related to a change that was made in the GitHub API a few days ago. A fix for that is already waiting for review, but I can't tell you how long it will take Apple to approve the app. 

Again, I feel very sorry for you and the other users that are having this poor experience. Please wait a few more days until the update will be available on the App Store.

Am 22.06.2011 um 20:03 schrieb pfig:

**Comment by dennisreimann** [comment]
Now that the new version is available on the App Store this should be fixed :)
