### ISSUE TITLE
Can't view all of my organization's repos

### ISSUE THREAD

**Issue by mayafish** [dennisreimann/ioctocat#112]
I'm only seeing 9 repos even though my organization has a total of 19. I'm an owner of the organization. They're private repos, if that makes a difference. Thanks!

**Comment by dennisreimann** [comment]
Hey, can you check if they are contained in the response for this request (executed on the command line):

curl -u mayafish:YOUR_PASSWORD https://github.com/api/v2/json/organizations/repositories

For me this returns private and public repos of all my organizations and they also show in iOctocat. I've also looked into the API docs for version 3, but organization repos aren't listed there or I just haven't found that in GitHub API v3.

**Comment by thedaniel** [comment]
@mayafish I was having the same issue. In my case, it was because I was using the Octokit library, which calls "/api/v2/json/organizations/#{org}/public_repositories" in its org_repos method. Check that your library uses /repositories, not /public_repositories

**Comment by hdoria** [comment]
I have the some problem. I can`t view my organization projects. I can't see my private projects. And i can't click on the "Organizations" buttons. It's grayed out.

**Comment by timofei7** [comment]
same here.  organizations is greyed out, then if i restart the app sometimes organizations (under feeds) works but when it tries to load the feed I get a "Loading Error:  Could not load the feed."

however i can see the private organization repositories fine, just not the feed.

**Comment by dennisreimann** [comment]
@timofei7 it's right, the org feeds aren't working at the moment, because we removed the API token from the app. GitHub is informed about the issue and I hope they will fix it soon. The problem is, that the org feeds are the only place that's left, where the API token is needed and the other feeds work with username/password.
