### ISSUE TITLE
Rendering messed up

### ISSUE THREAD

**Issue by greinacker** [dennisreimann/ioctocat#113]
When viewing the comments for an issue, the rendering is almost always messed up.  I can sometimes fix it by scrolling up to the top, or the bottom, or go back and forth a few times...but it's very inconsistent, and more often than not I see something like this:

![screenshot](http://i.imgur.com/S4mju.png)

**Comment by greinacker** [comment]
I should add, this is on an iPhone 4 running iOS 4.3.3

**Comment by greinacker** [comment]
Same problem on iPad, also running 4.3.3. This is all with the latest version of iOctocat downloaded from the app store.

**Comment by koraktor** [comment]
Can confirm this. (iPhone 4, iOS 4.3.3)

**Comment by cvx** [comment]
It is again a bug described in Issue #70. iPad-related code must have brought it back.

**Comment by dennisreimann** [comment]
Okay, I guess this is related to the TextCell changes, like @CvX said.

@CvX woud you like to look into this? I'm currently very busy and won't find the time to fix this during the next two weeks.

**Comment by cvx** [comment]
`UITextView` (as opposed to `UILabel` that we've been using before) is having a problem with resizing properly its parent view.
Played with code a little bit and I don't have any ideas on how to fix this issue. My previous trick, using `sizeWithFont`, doesn't make things any better this time.

**Comment by dennisreimann** [comment]
Okay, should we switch back to UILabel or what's your opinion on that?

Am 10.07.2011 um 22:43 schrieb CvX:

**Comment by cvx** [comment]
Using an UILabel would be a step back. At some point we'll need to parse all of these markdown formatting, urls, and such. And we need UITextView for displaying that stuff.
All I was saying was that **I** don't know how to solve this problem. I'm sure somebody can. :)

**Comment by jmeosbn** [comment]
I believe the op is referring to the app store version as I had the same issue, mostly the text was hidden until scrolling down and back up.

I noticed a lot of work had been done with text display so I compiled the current head and can
confirm it is much better, occasionally the text is clipped at the bottom though.

**Comment by jmeosbn** [comment]
@dbloete just noticed poster's screenshot and later comment confirms this is the appstore version and therefore the issue (as shown at least) is fixed for the current head. As I said before though, there is an occasional and slight clipping of the bottom of some (long?) comments.

**Comment by dennisreimann** [comment]
yep, I'm aware of that and trying to figure this out.
