### ISSUE TITLE
No longer showing feeds

### ISSUE THREAD

**Issue by jmeosbn** [dennisreimann/ioctocat#114]
"Loading Error - Could not load the feed". This started a couple of days ago and seems to apply to any feed (the main two, plus those on a user's profile).
Rest of the app works as usual - I'm posting this from it. ;)

**Comment by jmeosbn** [comment]
AppStore release has same issue, also occurred on issues list but unlike other feeds a retry worked.

**Comment by dennisreimann** [comment]
I can confirm this for "My Activity" and some org feeds. I really don't know why this is happening, especially as I can load the feeds via the URL just fine... and that's exactly what the app is doing. I'll investigate

**Comment by koraktor** [comment]
Seems to work again.

**Comment by jmeosbn** [comment]
Yep, here too (!?).

**Comment by dennisreimann** [comment]
That's weird. My Activity is working again, but some of my org feeds are still not working. I'd guess this is related to changes they are making to their API.

**Comment by koraktor** [comment]
@dbloete: Is this broken again? Feeds stopped working since updating to 1.4.1.

**Comment by dennisreimann** [comment]
which feeds stopped working for you? Did you check that your API token is available in the settings? 1.4.1 introduced the token again for feed requests.

**Comment by koraktor** [comment]
That's it. Thank you very much.

Maybe the error should mention that instead of just some generic error message.

**Comment by dennisreimann** [comment]
Good point, I'll add that. Glad that it works for you :)

**Comment by zedtux** [comment]
Sorry to post 7 months later, but I've buyed the application from the App Store, but when I launch it, I have this error in the "News feed" screen.

Other screens work well.

I tried to send to myself an email with the gitauth link, but I still have the error.
And I don't find any input field in settings where I could put my API token.

Could you give me some idea, or explanations?

**Comment by dennisreimann** [comment]
The update v1.4.4 removed the token as it is just needed for the organization feeds, which indeed aren't working at the moment. I wrote a mail to the GitHub support and they might look into this, as it is an API inconsistency.

However: We checked it here to see if the main feed isn't working, but for us it worked fine. Can you try again and report again if it still does not work for you?

**Comment by zedtux** [comment]
Yep, still failing with `Could not load the feed.` error message.

**Comment by dennisreimann** [comment]
Is there a way that you could debug this with Xcode?

**Comment by zedtux** [comment]
I never done this before, but if you explain me how can I do that, I'm your man!

Don't know if a developer account is necessary for this, but if yes, I could start thinking of having one...
Just let me know.

**Comment by dennisreimann** [comment]
You can clone the code and open the project in Xcode. After that, select "iOctocat > iPhone Simulator" in the upper left corner and hit the play button. This should build the app and open it in the simulator.

You can activate the debug console by selecting "View > Debug Area > Activate Console". There you will find the debugging output. Please clear it (Cmd + K) and fill in your credentials in the simulator. After submitting the form, whats the output in the console?

If you get stuck somewhere in between, please ask again, so that I can help.

**Comment by dennisreimann** [comment]
btw: A developer account should not be necessary for that!

**Comment by zedtux** [comment]
Cool. Do you any tutorial to do it?

**Comment by dennisreimann** [comment]
What do you mean by tutorial? For Xcode?

Are the described steps working for you?

**Comment by zedtux** [comment]
Oops... Sorry. I didn't took time to read the steps to enable debug.

I will do it today and let you know.

**Comment by zedtux** [comment]
> select "iOctocat > iPhone Simulator" in the upper left corner and hit the play button. This should build the app and open it in the simulator.

Sorry, but no. I have this exception:

```
'ASIFormDataRequest.h' file not found
In file included from ../ioctocat/Classes/GHFeed.h:2:
In file included from ../ioctocat/Classes/GHFeed.m:1:
'ASIFormDataRequest.h' file not found in ../ioctocat/Classes/GHResource.h
```

I've cloned with git the code, then open Xcode and imported the project. Selected `iPhone 5.0 Simulator`, then click on **Run**.

**Comment by dennisreimann** [comment]
I'm sorry, my fault. I just extended the README with some debugging information:
https://github.com/dbloete/ioctocat/blob/master/README.md

I forgot to mention the second step: You have to run `git submodule update` inside the project directory (in the Terminal)

**Comment by zedtux** [comment]
`git submodule update` return immediately without doing anything, and the build still fail with the same error

**Comment by koraktor** [comment]
You have to use `git submodule update --init` so the submodule gets initialized first.

**Comment by zedtux** [comment]
> You have to use git submodule update --init so the submodule gets initialized first.

Nice!

**Comment by zedtux** [comment]
Here is the content of the https://gist.github.com/1951710

**Comment by koraktor** [comment]
Looks like you used your mail address "zedtux@zedroot.org" for the login instead of just your GitHub username "zedtux" (see the URL in line 34 of your Gist). This 404 error should be handled by iOctocat though.

**Comment by zedtux** [comment]
Okay, thank you. I will try it.

**Comment by zedtux** [comment]
It's working with the user name!

Thank you!

But it's strange that some part of the application work, and some other not.

**Comment by dennisreimann** [comment]
Nice, nevertheless I'll push some fixes for this problem :)

Glad that it worked out for you - and thanks for helping to debug this!

**Comment by dennisreimann** [comment]
Okay, I pushed some fixes for the errors that occurred.

**Comment by alanmiller** [comment]
Sorry to ask the same question 4 months later but...
when I run 
  git submodule update --init
from my ioctocat dir, I get this:
  Submodule 'Classes/External/ASIHttpRequest' () registered for path 'Classes/External/ASIHttpRequest'
  Cloning into 'Classes/External/ASIHttpRequest'...
  fatal: unable to connect to github.com:
  github.com[0: 207.97.227.239]: errno=Operation timed out

While the git command is running I can see that it actually created the
Classes/External/ASIHttpRequest directory and .git sub-dir but after a minute or so it fails 

Is it a connection problem or a repo problem? 
The ssh connection works:
  [My-Mac-Mini:ioctocat]$ ssh -T git@github.com
  Hi alanmiller! You've successfully authenticated, but GitHub does not provide shell access.

  [My-Mac-Mini:ioctocat]$ cat /Users/amiller/.ssh/config 
  Host github.com
    Hostname ssh.github.com
    Port 443

**Comment by dennisreimann** [comment]
I think your ssh config messes it up. It can't clone the submodules from github.com, because it will try to get it from ssh.github.com

**Comment by klaustopher** [comment]
Thought about maybe moving to [Cocoapods](http://cocoapods.org/) for the dependencies?

**Comment by alanmiller** [comment]
Thanks, no worries. I cloned the submodule separately, copied in the files manually and was able to build and deploy it. 

Cool, my very first build.  Im new to xcode/iOS.

**Comment by dennisreimann** [comment]
nice, have fun!
