### ISSUE TITLE
Gist support

### ISSUE THREAD

**Issue by jelder** [dennisreimann/ioctocat#119]
Maybe this is out of scope, but Gist support would be insanely useful.

**Comment by springrider** [comment]
agree, like this one: http://itunes.apple.com/in/app/gitapp/id449479210?mt=8

**Comment by benwoody** [comment]
This would be nice. Right now, clicking a gist link opens a profile page for the gist, which breaks.

**Comment by mkelley33** [comment]
Has anyone done any work on this issue? When I click a gist link, I too get errors.

**Comment by dennisreimann** [comment]
I'll fix the bug and ship it with the next release. Integrating Gists will take a bit more time, though.

**Comment by mkelley33** [comment]
Thank you, I'm looking forward to it.  I totally understand time-constraints. Maybe when I get some time I'll be fortunate enough code up something fun and submit a pull request to this project :)

**Comment by benwoody** [comment]
Best commit yet. Well implemented.

**Comment by mkelley33** [comment]
Excellent. What a great addition!

**Comment by dennisreimann** [comment]
You are talking about the Gist support that just hit the store? If that's the case, look forward to v1.6.0 to be released soon, because it will also give you a repository browser that has a code view works much like the Gist viewer.
