### ISSUE TITLE
Inbox access

### ISSUE THREAD

**Issue by JakeWharton** [dennisreimann/ioctocat#12]
Allow sending, reading, replying, and general management of the inbox. It might be useful to make this a tab in the toolbar (with a count of unread messages).

**Comment by dennisreimann** [comment]
That would be great, but the current API state does not support this. We'll keep this as a feature request on hold and implement it when the API supports it.

**Comment by dennisreimann** [comment]
I filed a ticket for that: http://support.github.com/discussions/api/67-feature-request-add-the-inbox-to-the-api

**Comment by dennisreimann** [comment]
Now that GitHub removed the Inbox, this is no longer necessary.
