### ISSUE TITLE
Login broken?

### ISSUE THREAD

**Issue by rscpp** [dennisreimann/ioctocat#120]
I am trying to login with correct details and am told they are either incorrect or I don't have an Internet connection. Details are correct and I do habe a connection. What can I do?

**Comment by dennisreimann** [comment]
Can you check that the API Token is also provided? (in the Settings.app)

**Comment by rscpp** [comment]
Hi thanks for your response. Yes it is set in the app and also settings app.

Kind Regards,

Tommy

## 

Tommy Newman MEng (Hons)
Technical Director
RSCPP Ltd - connecting people with therapists across the UK 
http://www.rscpp.co.uk/ www.rscpp.co.uk

RSCPP Ltd. Registered in England and Wales. Company No. 6285631.
Registered Office: 31 Springfield Park, Twyford, Reading, Berkshire. RG10
9JG. UK.
Telephone: 0800 5345 305. Email:  mailto:tommy.newman@rscpp.co.uk
tommy.newman@rscpp.co.uk

Our business grows by referrals. We would really appreciate you telling
therapists and people who may benefit from therapy about
http://www.rscpp.co.uk/ www.rscpp.co.uk. Thank you.

This email is subject to the RSCPP Terms & Conditions & Privacy Policy at
http://www.rscpp.co.uk/ www.rscpp.co.uk. The information in this email is
confidential and is intended solely for the addressee. If you are not the
intended addressee please contact us immediately.

Consider the environment. Do you need to print this email?

**Comment by dennisreimann** [comment]
Hey Tommy, I checked with some people and for them and me it's working fine. I guess you are using the latest version - can you try to shut down the app completely (remove it from memory by tapping the home button twice and then remove it from the list of apps that appears on the bottom of the screen). 

Sorry for the inconveniences!

**Comment by rscpp** [comment]
Hi,

Yes am using the latest app, I just purchased it 2 days ago. I removed it
from memory and opened it again but it is still not working.

Perhaps you are able to debug it by looking at your end for my login
attempts for tommy@rscpp.co.uk?

Kind Regards,

Tommy

## 

Tommy Newman MEng (Hons)
Technical Director
RSCPP Ltd - connecting people with therapists across the UK 
www.rscpp.co.uk

RSCPP Ltd. Registered in England and Wales. Company No. 6285631. VAT
Registration Number 990 4178 95.
Registered Office: 31 Springfield Park, Twyford, Reading, Berkshire. RG10
9JG. UK.
Telephone: 0800 5345 305. Email: tommy.newman@rscpp.co.uk

Our business grows by referrals. We would really appreciate you telling
therapists and people who may benefit from therapy about www.rscpp.co.uk.
Thank you.

This email is subject to the RSCPP Terms & Conditions & Privacy Policy at
www.rscpp.co.uk. The information in this email is confidential and is
intended solely for the addressee. If you are not the intended addressee
please contact us immediately.

Consider the environment. Do you need to print this email?

-----Original Message-----
From: Dennis Reimann
[mailto:reply+i-2527894-2acba34f0b61d5fe976bdfd44fe3d3bfedf0b44f-210694@repl
y.github.com] 
Sent: 13 December 2011 08:55
To: rscpp
Subject: Re: [ioctocat] Login broken? (#120)

Hey Tommy, I checked with some people and for them and me it's working fine.
I guess you are using the latest version - can you try to shut down the app
completely (remove it from memory by tapping the home button twice and then
remove it from the list of apps that appears on the bottom of the screen). 

Sorry for the inconveniences!

---

**Comment by koraktor** [comment]
> Perhaps you are able to debug it by looking at your end for my login attempts for tommy@rscpp.co.uk?

This won't work as authentication is directly passed to GitHub.

But you're probably using the wrong credentials. I'm only using my nickname (koraktor) to login with iOctocat, not the mail address like you (probably) are.

**Comment by dennisreimann** [comment]
Hey Tommy, I can't check it from here, because there is nothing in between the app and GitHub. Are there any special characters in your password?

**Comment by rscpp** [comment]
Thanks, yes I was using the email address, but I've now changed it to use my
nickname, and I still have the same issue.

I have noticed that I add the API key in the settings.app, and it isn't
there when I go in to iOctocat to login, by default, so I add it there too.
I enter the password too.

Any other ideas?

Kind Regards,

Tommy

## 

Tommy Newman MEng (Hons)
Technical Director
RSCPP Ltd - connecting people with therapists across the UK 
www.rscpp.co.uk

RSCPP Ltd. Registered in England and Wales. Company No. 6285631. VAT
Registration Number 990 4178 95.
Registered Office: 31 Springfield Park, Twyford, Reading, Berkshire. RG10
9JG. UK.
Telephone: 0800 5345 305. Email: tommy.newman@rscpp.co.uk

Our business grows by referrals. We would really appreciate you telling
therapists and people who may benefit from therapy about www.rscpp.co.uk.
Thank you.

This email is subject to the RSCPP Terms & Conditions & Privacy Policy at
www.rscpp.co.uk. The information in this email is confidential and is
intended solely for the addressee. If you are not the intended addressee
please contact us immediately.

Consider the environment. Do you need to print this email?

-----Original Message-----
From: Sebastian Staudt
[mailto:reply+i-2527894-2acba34f0b61d5fe976bdfd44fe3d3bfedf0b44f-210694@repl
y.github.com] 
Sent: 13 December 2011 10:35
To: rscpp
Subject: Re: [ioctocat] Login broken? (#120)

> Perhaps you are able to debug it by looking at your end for my login 
> attempts for tommy@rscpp.co.uk?

This won't work as authentication is directly passed to GitHub.

But you're probably using the wrong credentials. I'm only using my nickname
(koraktor) to login with iOctocat, not the mail address like you (probably)
are.

---

**Comment by dennisreimann** [comment]
That's weird, we checked it again so the API is working. Does your password contain any special characters?

Do you have an iOS Dev account so that you could compile the code and look at the API response? Sorry, I know this would be painful, but from what I see there is no change to debug it by doing something else.

**Comment by rscpp** [comment]
No weird characters no, just alphanumeric.

Sorry I'm not a iOS dev no.

I will try clearing all passwords/keys and reinserting afresh to eliminate
any issue there, later, if I have no luck, I don't know if its possible to
cancel the order and get a refund?

Kind Regards,

Tommy

## 

Tommy Newman MEng (Hons)
Technical Director
RSCPP Ltd - connecting people with therapists across the UK 
www.rscpp.co.uk

RSCPP Ltd. Registered in England and Wales. Company No. 6285631. VAT
Registration Number 990 4178 95.
Registered Office: 31 Springfield Park, Twyford, Reading, Berkshire. RG10
9JG. UK.
Telephone: 0800 5345 305. Email: tommy.newman@rscpp.co.uk

Our business grows by referrals. We would really appreciate you telling
therapists and people who may benefit from therapy about www.rscpp.co.uk.
Thank you.

This email is subject to the RSCPP Terms & Conditions & Privacy Policy at
www.rscpp.co.uk. The information in this email is confidential and is
intended solely for the addressee. If you are not the intended addressee
please contact us immediately.

Consider the environment. Do you need to print this email?

-----Original Message-----
From: Dennis Reimann
[mailto:reply+i-2527894-2acba34f0b61d5fe976bdfd44fe3d3bfedf0b44f-210694@repl
y.github.com] 
Sent: 13 December 2011 13:45
To: rscpp
Subject: Re: [ioctocat] Login broken? (#120)

That's weird, we checked it again so the API is working. Does your password
contain any special characters?

Do you have an iOS Dev account so that you could compile the code and look
at the API response? Sorry, I know this would be painful, but from what I
see there is no change to debug it by doing something else.

---

**Comment by dennisreimann** [comment]
I think it is possible to return an app on the App Store, though I haven't done this before. Feel free to do so, if all else fails :)

**Comment by rscpp** [comment]
It strangely started working!

Kind Regards,

Tommy

## 

Tommy Newman MEng (Hons)
Technical Director
RSCPP Ltd - connecting people with therapists across the UK 
www.rscpp.co.uk

RSCPP Ltd. Registered in England and Wales. Company No. 6285631. VAT
Registration Number 990 4178 95.
Registered Office: 31 Springfield Park, Twyford, Reading, Berkshire. RG10
9JG. UK.
Telephone: 0800 5345 305. Email: tommy.newman@rscpp.co.uk

Our business grows by referrals. We would really appreciate you telling
therapists and people who may benefit from therapy about www.rscpp.co.uk.
Thank you.

This email is subject to the RSCPP Terms & Conditions & Privacy Policy at
www.rscpp.co.uk. The information in this email is confidential and is
intended solely for the addressee. If you are not the intended addressee
please contact us immediately.

Consider the environment. Do you need to print this email?

-----Original Message-----
From: Dennis Reimann
[mailto:reply+i-2527894-2acba34f0b61d5fe976bdfd44fe3d3bfedf0b44f-210694@repl
y.github.com] 
Sent: 13 December 2011 14:52
To: rscpp
Subject: Re: [ioctocat] Login broken? (#120)

I think it is possible to return an app on the App Store, though I haven't
done this before. Feel free to do so, if all else fails :)

---

**Comment by dennisreimann** [comment]
I'm glad that it works for you now.
