### ISSUE TITLE
Can log in, but not see any repositories/feeds/activity

### ISSUE THREAD

**Issue by vrai** [dennisreimann/ioctocat#121]
I get past the login/authentication screen but the following error box appears multiple times afterwards ...

``` text
Loading error
Could not load the feed. Please ensure that you are providing your API token. You can set the token in the app settings.
```

Toggling between "News Feed" and "My Activity" results in the same error. Selecting the "Repositories" tab causes the following error to appear five times over ...

``` text
Loading error
Could not load the repositories
```

Selecting profile displays the correct details (location, blog, etc) and even shows the list of repositories. However the "Organizations" section stays in the loading state and eventually the following errors appear ...

``` text
Loading error
Could not load the list of organizations
```

``` text
Loading error
Could not load the organizations
```

I've confirmed that my user name, password and API token are all present and correct. My connection to the internet isn't the fastest but it is reliable.

**Comment by dennisreimann** [comment]
Sometimes this is related to API hiccups, does it still occur?

**Comment by vrai** [comment]
The problem occurs on an intermittent basis, but the App seems to work most of the time.

**Comment by koraktor** [comment]
Since the newest update this happens almost all the time for me. Closing the app does not help.

**Comment by dennisreimann** [comment]
Are you talking about the master branch or the latest App Store version (1.4.3)?

**Comment by koraktor** [comment]
1.4.3 from App Store.

Funny thing is, yesterday and today it worked without problems. But I'm pretty sure I didn't hit any API limits before.

**Comment by dennisreimann** [comment]
Hmm, personally my experience is, that v3 of the GitHub API is a lot more stable than v2 was…
