### ISSUE TITLE
Feature request: github Enterprise Support

### ISSUE THREAD

**Issue by wolfgangpfnuer** [dennisreimann/ioctocat#127]
My company is using github Enterprise (local copy of github).
It would be nice to be able to choose a secondary github URL with a secondary Login.

Maybe Switch in preferences?

**Comment by dennisreimann** [comment]
Does GitHub Enterprise offer the same API as the normal Github does? If so it would be possible to define a custom endpoint.

**Comment by dennisreimann** [comment]
I've sent an email to the GitHub support asking about that. I'll keep you posted!

**Comment by klaustopher** [comment]
It has API v3 (https://enterprise.github.com/faq#faq-7) and there is an access guide: https://support.enterprise.github.com/entries/21391237-using-the-api

**Comment by dennisreimann** [comment]
Nice, now I got all the infos I needed. Together with multi-user support, enabling iOctocat for GitHub Enterprise is the next thing on my Todo list :)

**Comment by wolfgangpfnuer** [comment]
While I still think this would be a cool Feature (and maybe selling point for some), my personal need was diminished by a company switch ;-)

**Comment by dennisreimann** [comment]
It's theoretically done, who can test it?

**Comment by jsbattig** [comment]
I can test it. We have a local install of github enterprise.
Dont know where to configure the url though

**Comment by dennisreimann** [comment]
@jsbattig with the Pro Upgrade of iOctocat v2 (http://ioctocat.com/appstore) you can add Enterprise accounts just like github.com accounts.
