### ISSUE TITLE
Hide empty repository groups

### ISSUE THREAD

**Issue by JakeWharton** [dennisreimann/ioctocat#13]
Do not display repository groups (public/private) that are empty. Maybe make it an option that is enabled by default.

**Comment by dennisreimann** [comment]
Now that there is the Profile view, the "Repositories" tab is somewhat redundant - what about removing the repositories tab?

**Comment by JakeWharton** [comment]
Personally, I thought the Profile tab was going to transition more into something like account management. I know that now it uses the User view which we see browsing other users. From a UI design and usability standpoint I think the repositories tab is a logical design piece. If it were me, I would move the profile tab to the far right and create an Account view displayed there which mirrors the User view except replaces the with account control over emails, ssh, etc. I had hoped the repositories tab would evolve into allowing me to view gists as well, perhaps through a header toolbar switcher. This is only my opinion though, and what you said would certainly remove no functionality whatsoever.

**Comment by intabulas** [comment]
right now the only "Account" api's that exist are adding and removing keys and email addresses. I guess you can also consider following/unfollowing (and watched) part of an account tab..

Interesting point about gists.. there isnt an "official" api yet, but there is a somewhat semi-official start of one 

see http://gist.github.com/4277

**Comment by dennisreimann** [comment]
I'm closing this.
