### ISSUE TITLE
Repositories view crashes

### ISSUE THREAD

**Issue by koraktor** [dennisreimann/ioctocat#130]
The "Repositories" view crashes for me on iPad and iPhone. I can't say exactly when this happened first, but I guess it's not caused by an iOctocat update.

**Comment by dennisreimann** [comment]
Checked it on the iPhone simulator and my iPad, for me it's working. Maybe it is related to something in your repo lists, can you check if this still occurs. If so, can you open it in Xcode and send the debugging output?

**Comment by koraktor** [comment]
I did manage to find the cause of the problem and fixed it myself. Please see the pull request above.
