### ISSUE TITLE
crash on repositories list

### ISSUE THREAD

**Issue by cvx** [dennisreimann/ioctocat#134]
Crashes when loading repositories

**Comment by dennisreimann** [comment]
Which version did you try it with? Can you please pull the current master and see if the problem still exists? Thanks! :)

**Comment by cvx** [comment]
It happend last night on my friend's device. I'll try again tomorrow with the same user on current master.
Also the app store version crashed on my iPhone just after sending this bug report. I have the crash report - will investigate on that later. :)

**Comment by cboebel** [comment]
I just experienced the same issue. I just installed (from the app store) three days ago.

I was looking at my repos. I unstarred a repo, and then I stopped watching a repo. When it went back to the repo list, it crashed. Closing the program, restarting, and going to the repos list still causes a crash. I will download and run from your github repository to see if it's still happening with that.

**Comment by dennisreimann** [comment]
@cboebel please try it with v1.6.1 (which was released yesterday) first. I will also have a look at the case you described, thanks for reporting it!
