### ISSUE TITLE
Unable to log in.

### ISSUE THREAD

**Issue by michaeljaggers** [dennisreimann/ioctocat#136]
Latest version of ios. 
iPhone 4
Latest AppStore ioctocat version.

Using my username: jaggermeister
Password is all normal alphanumeric characters.

Authentication fails repeatedly and popup tells me to make sure I am connected to the Internet (which I am) and ensure username and password are correct ( they are).

Same result both on wifi and 3G.
In settings.app my username and password are populated correctly.

....What's the deal here ?

**Comment by dennisreimann** [comment]
See #135. The app is currently in review and should be on the App Store within the next few hours. I'm sorry for the inconveniences, but this is caused by a recent GitHub API change...

**Comment by michaeljaggers** [comment]
No prob! Thanks for the quick response.

**Comment by dennisreimann** [comment]
test
