### ISSUE TITLE
Unable to build with XCode 4.2

### ISSUE THREAD

**Issue by oncleben31** [dennisreimann/ioctocat#139]
I've try to compile ioctocat with Xcode 4.2 (target iPhone 4.3 Simulator) on SL on my iMac and it raises some errors : See below
Is it a bug or do I do something wrong ?

Build target iOctocat

CompileC /Users/iMac/Library/Developer/Xcode/DerivedData/iOctocat-cflprtgqueyqhycnmdydzmpuymqz/Build/Intermediates/iOctocat.build/Debug-iphonesimulator/iOctocat.build/Objects-normal/i386/AuthenticationController.o Classes/AuthenticationController.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/iMac/Developpement/iOS/ioctocat
    setenv LANG en_US.US-ASCII
    setenv PATH "/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin:/opt/local/bin:/usr/local/git/bin"
    /Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin/clang -x objective-c -arch i386 -fmessage-length=0 -fdiagnostics-print-source-range-info -fdiagnostics-show-category=id -fdiagnostics-parseable-fixits -std=c99 -Wno-trigraphs -fpascal-strings -O0 -Wreturn-type -Wparentheses -Wswitch -Wno-unused-parameter -Wunused-variable -Wunused-value -Wno-shorten-64-to-32 -DDEBUG=1 -isysroot /Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator5.0.sdk -fexceptions -fasm-blocks -mmacosx-version-min=10.6 -gdwarf-2 -fvisibility=hidden -Wno-sign-conversion -fobjc-abi-version=2 -fobjc-legacy-dispatch "-DIBOutlet=**attribute**((iboutlet))" "-DIBOutletCollection(ClassName)=**attribute**((iboutletcollection(ClassName)))" "-DIBAction=void)**attribute**((ibaction)" -D__IPHONE_OS_VERSION_MIN_REQUIRED=40000 -iquote /Users/iMac/Library/Developer/Xcode/DerivedData/iOctocat-cflprtgqueyqhycnmdydzmpuymqz/Build/Intermediates/iOctocat.build/Debug-iphonesimulator/iOctocat.build/iOctocat-generated-files.hmap -I/Users/iMac/Library/Developer/Xcode/DerivedData/iOctocat-cflprtgqueyqhycnmdydzmpuymqz/Build/Intermediates/iOctocat.build/Debug-iphonesimulator/iOctocat.build/iOctocat-own-target-headers.hmap -I/Users/iMac/Library/Developer/Xcode/DerivedData/iOctocat-cflprtgqueyqhycnmdydzmpuymqz/Build/Intermediates/iOctocat.build/Debug-iphonesimulator/iOctocat.build/iOctocat-all-target-headers.hmap -iquote /Users/iMac/Library/Developer/Xcode/DerivedData/iOctocat-cflprtgqueyqhycnmdydzmpuymqz/Build/Intermediates/iOctocat.build/Debug-iphonesimulator/iOctocat.build/iOctocat-project-headers.hmap -I/Users/iMac/Library/Developer/Xcode/DerivedData/iOctocat-cflprtgqueyqhycnmdydzmpuymqz/Build/Products/Debug-iphonesimulator/include -I/Users/iMac/Library/Developer/Xcode/DerivedData/iOctocat-cflprtgqueyqhycnmdydzmpuymqz/Build/Intermediates/iOctocat.build/Debug-iphonesimulator/iOctocat.build/DerivedSources/i386 -I/Users/iMac/Library/Developer/Xcode/DerivedData/iOctocat-cflprtgqueyqhycnmdydzmpuymqz/Build/Intermediates/iOctocat.build/Debug-iphonesimulator/iOctocat.build/DerivedSources -F/Users/iMac/Library/Developer/Xcode/DerivedData/iOctocat-cflprtgqueyqhycnmdydzmpuymqz/Build/Products/Debug-iphonesimulator -include /Users/iMac/Library/Developer/Xcode/DerivedData/iOctocat-cflprtgqueyqhycnmdydzmpuymqz/Build/PrecompiledHeaders/iOctocat_Prefix-fdjyakowanqjrzaosjdbmhbxmizg/iOctocat_Prefix.pch -MMD -MT dependencies -MF /Users/iMac/Library/Developer/Xcode/DerivedData/iOctocat-cflprtgqueyqhycnmdydzmpuymqz/Build/Intermediates/iOctocat.build/Debug-iphonesimulator/iOctocat.build/Objects-normal/i386/AuthenticationController.d -c /Users/iMac/Developpement/iOS/ioctocat/Classes/AuthenticationController.m -o /Users/iMac/Library/Developer/Xcode/DerivedData/iOctocat-cflprtgqueyqhycnmdydzmpuymqz/Build/Intermediates/iOctocat.build/Debug-iphonesimulator/iOctocat.build/Objects-normal/i386/AuthenticationController.o

/Users/iMac/Developpement/iOS/ioctocat/Classes/AuthenticationController.m:16:7: error: property 'account' not found on object of type 'AuthenticationController *'; did you mean to access ivar 'account'? [3]
         self.account = nil;
             ~^
             ->
fix-it:"/Users/iMac/Developpement/iOS/ioctocat/Classes/AuthenticationController.m":{16:6-16:7}:"->"
1 error generated.

CompileC /Users/iMac/Library/Developer/Xcode/DerivedData/iOctocat-cflprtgqueyqhycnmdydzmpuymqz/Build/Intermediates/iOctocat.build/Debug-iphonesimulator/iOctocat.build/Objects-normal/i386/GHSearch.o Classes/GHSearch.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/iMac/Developpement/iOS/ioctocat
    setenv LANG en_US.US-ASCII
    setenv PATH "/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin:/opt/local/bin:/usr/local/git/bin"
    /Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin/clang -x objective-c -arch i386 -fmessage-length=0 -fdiagnostics-print-source-range-info -fdiagnostics-show-category=id -fdiagnostics-parseable-fixits -std=c99 -Wno-trigraphs -fpascal-strings -O0 -Wreturn-type -Wparentheses -Wswitch -Wno-unused-parameter -Wunused-variable -Wunused-value -Wno-shorten-64-to-32 -DDEBUG=1 -isysroot /Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator5.0.sdk -fexceptions -fasm-blocks -mmacosx-version-min=10.6 -gdwarf-2 -fvisibility=hidden -Wno-sign-conversion -fobjc-abi-version=2 -fobjc-legacy-dispatch "-DIBOutlet=**attribute**((iboutlet))" "-DIBOutletCollection(ClassName)=**attribute**((iboutletcollection(ClassName)))" "-DIBAction=void)**attribute**((ibaction)" -D__IPHONE_OS_VERSION_MIN_REQUIRED=40000 -iquote /Users/iMac/Library/Developer/Xcode/DerivedData/iOctocat-cflprtgqueyqhycnmdydzmpuymqz/Build/Intermediates/iOctocat.build/Debug-iphonesimulator/iOctocat.build/iOctocat-generated-files.hmap -I/Users/iMac/Library/Developer/Xcode/DerivedData/iOctocat-cflprtgqueyqhycnmdydzmpuymqz/Build/Intermediates/iOctocat.build/Debug-iphonesimulator/iOctocat.build/iOctocat-own-target-headers.hmap -I/Users/iMac/Library/Developer/Xcode/DerivedData/iOctocat-cflprtgqueyqhycnmdydzmpuymqz/Build/Intermediates/iOctocat.build/Debug-iphonesimulator/iOctocat.build/iOctocat-all-target-headers.hmap -iquote /Users/iMac/Library/Developer/Xcode/DerivedData/iOctocat-cflprtgqueyqhycnmdydzmpuymqz/Build/Intermediates/iOctocat.build/Debug-iphonesimulator/iOctocat.build/iOctocat-project-headers.hmap -I/Users/iMac/Library/Developer/Xcode/DerivedData/iOctocat-cflprtgqueyqhycnmdydzmpuymqz/Build/Products/Debug-iphonesimulator/include -I/Users/iMac/Library/Developer/Xcode/DerivedData/iOctocat-cflprtgqueyqhycnmdydzmpuymqz/Build/Intermediates/iOctocat.build/Debug-iphonesimulator/iOctocat.build/DerivedSources/i386 -I/Users/iMac/Library/Developer/Xcode/DerivedData/iOctocat-cflprtgqueyqhycnmdydzmpuymqz/Build/Intermediates/iOctocat.build/Debug-iphonesimulator/iOctocat.build/DerivedSources -F/Users/iMac/Library/Developer/Xcode/DerivedData/iOctocat-cflprtgqueyqhycnmdydzmpuymqz/Build/Products/Debug-iphonesimulator -include /Users/iMac/Library/Developer/Xcode/DerivedData/iOctocat-cflprtgqueyqhycnmdydzmpuymqz/Build/PrecompiledHeaders/iOctocat_Prefix-fdjyakowanqjrzaosjdbmhbxmizg/iOctocat_Prefix.pch -MMD -MT dependencies -MF /Users/iMac/Library/Developer/Xcode/DerivedData/iOctocat-cflprtgqueyqhycnmdydzmpuymqz/Build/Intermediates/iOctocat.build/Debug-iphonesimulator/iOctocat.build/Objects-normal/i386/GHSearch.d -c /Users/iMac/Developpement/iOS/ioctocat/Classes/GHSearch.m -o /Users/iMac/Library/Developer/Xcode/DerivedData/iOctocat-cflprtgqueyqhycnmdydzmpuymqz/Build/Intermediates/iOctocat.build/Debug-iphonesimulator/iOctocat.build/Objects-normal/i386/GHSearch.o

/Users/iMac/Developpement/iOS/ioctocat/Classes/GHSearch.m:30:104: error: property 'resourceURL' not found on object of type 'GHSearch *' [3]
     return [NSString stringWithFormat:@"<GHSearch searchTerm:'%@' resourceURL:'%@'>", searchTerm, self.resourceURL];
                                                                                                        ^
1 error generated.

**Comment by dennisreimann** [comment]
I can't reproduce it as I'm using the current Xcode (4.3.3) on Lion. Is it the current master you are working on?

**Comment by oncleben31** [comment]
Yes Current master with the last commit you've done yesterday. I'm stuck with Snow Leopard so I can't update to 4.3.3. What can I do to help you make it work ?

**Comment by oncleben31** [comment]
i've try to correct myself. See https://github.com/dennisreimann/ioctocat/pull/141

**Comment by oncleben31** [comment]
Tested and validated.
