### ISSUE TITLE
High-resolution icons

### ISSUE THREAD

**Issue by aharren** [dennisreimann/ioctocat#144]
Some icons are not available in @2x high-resolution, e.g. the TabBarOrgs icon and some toolbar icons.

**Comment by dennisreimann** [comment]
I added some more (000af2dd1e9ab838e6f60eb06f4aa2b0577f35fd), but I'll have to look for another free icon set which we could use…

**Comment by aharren** [comment]
Thx!

Sent from iOctocat

**Comment by aharren** [comment]
Great!
