### ISSUE TITLE
Move News Feed/My Feed into header toolbar

### ISSUE THREAD

**Issue by JakeWharton** [dennisreimann/ioctocat#15]
The news feed/my feed buttons should be moved into the header toolbar so they can be accessed independently of the list. The title "My Feeds" is redundant since it is also in the bottom toolbar anyways.

**Comment by dennisreimann** [comment]
Moved News Feed/My Feed into header toolbar. Closed by 3c1044ff4fe37d6820bb4e50e07faf51aa9f891f
