### ISSUE TITLE
Can't load branch specific feed

### ISSUE THREAD

**Issue by grmwld** [dennisreimann/ioctocat#151]
Hi, I encountered a little problem. Hopefully it should be a quick fix. I would have been glad to post a pull request, but I'm absolutely incompetent in Obj-C

When I try to load the feeds of a specific branch, it works quite fine with the majority of repos, but in some it does not.

I think github sanitizes the repo name, so that any repo feed whose name contains a "." (dot) cannot be found at the address octocat is hitting.

Alternativeley, I think every branch repo has an atom feed at
`https://github.com/**username**/**repo-name**/commits/**branch**.atom`

**Comment by dennisreimann** [comment]
Thanks for reporting that, I'll check and fix this soon

**Comment by dennisreimann** [comment]
Thanks a lot, you analysis was right on! I'll release a new version for the App Store with that fix soon.

**Comment by grmwld** [comment]
No problem ^^

It's a pleasure to, even on a tiny scale, contribute to making this wonderful app even better.
