### ISSUE TITLE
Clicking 'Starred' events in the feed stops app

### ISSUE THREAD

**Issue by benwoody** [dennisreimann/ioctocat#155]
Github introduced 'Starring' repos.  These events are showing up in the Feed list and selecting the item breaks the app.

Not sure how/if this changed how their API works, but that might also change how Watching works as well.

ps.
Love how you added iOctocat issues/feedback. Very meta to use Github in-app to track issues :+1:

**Comment by dennisreimann** [comment]
Thanks for reporting that! I'll fix this asap and hope to be able to integrate starring as a new feature when the API for that becomes available.
