### ISSUE TITLE
Feature Request: Star/Favorite Specific Repositories & Have an Activity Feed For Them

### ISSUE THREAD

**Issue by JohnPostlethwait** [dennisreimann/ioctocat#156]
I am part of a large organization and we have a TON of changes/comments going on at any given time. I am part of only a couple repos of our organization. It would be great if I could favorite or star these specific repositories and get a sort of customized list of activities for these repositories that I have starred in this app so that I can better keep up with the parts of the organization that are relevant to me.

**Comment by dennisreimann** [comment]
Yep, nice idea. Like mentioned in #157 this will be a lot easier, when we switch from using the events feed to the real events api. Thanks for your feedback!

**Comment by dennisreimann** [comment]
Would this be just for the repo events or something like quick access to the page of the repository? 

I think aggregating many repository feeds will be tough, because we will have to load them one by one and then merge the results. It's doable, but does not scale for more than five repo feeds.

**Comment by JohnPostlethwait** [comment]
This would be for events (pull requests, comments, branches, forks, etc) on the repos I've favorited in ioctocat. 

I'm not familiar with the API, but it seems like you'd already have the data cached in the current News feed that could then just be filtered...

**Comment by dennisreimann** [comment]
Okay, so just a filtered version of the current user and org feeds?

That'd work nicely together with a bookmark list for quick repo access (which I am also planning to add).

**Comment by JohnPostlethwait** [comment]
Yeah, basically: I just want to less noisy version of the current feed so I can pick out the events I really care about.
