### ISSUE TITLE
feed not updating

### ISSUE THREAD

**Issue by weakfl** [dennisreimann/ioctocat#158]
I don't get any new messages in the 'Feeds' tab anymore. Last message is from 3 months ago.
I don't get an error message either. It just updates but doesn't add any new entries to my feeds.

**Comment by dennisreimann** [comment]
Did you try completely restarting the app? what happens when you pull to refresh the table view?

**Comment by weakfl** [comment]
Yes, I even completely deinstalled the app and installed the latest build. Refreshing the table view doesn't help either.

I'm wondering if it has to do with my github account (settings)?

**Comment by weakfl** [comment]
I think it has indeed to do with my github account.
All repos I was watching previously had changed to starred only. I've now started watching again, lets see if that helps...

**Comment by weakfl** [comment]
was indeed related to my github settings. closing.

**Comment by dennisreimann** [comment]
test
