### ISSUE TITLE
UI Change for bottom row

### ISSUE THREAD

**Issue by benwoody** [dennisreimann/ioctocat#166]
With all the awesome new features you're adding :wink: , the menu at the bottom of the screen and the 'more' menu are starting to get cluttered. 

Would it make sense to remove that menu bar altogether and move to a "swipe right" to open menu like the facebook app has?

That would leave more room at the bottom for the feed and other open pages and you'd be able to sort and divide up the menu if it were a full navigation list.

Just my 2 cents.

**Comment by dennisreimann** [comment]
yeah, good point. I've been thinking about other majro UI/UX changes lately as well, because the UI feels somehow dated - it didn't really change since the app was born a few years ago. Keep your thoughts on that coming, I'm hearing you :)

**Comment by dennisreimann** [comment]
This is how it looks now: 

![ioctocat-new-menu.png](https://f.cloud.github.com/assets/886/2058/0effe4f8-4180-11e2-904d-f87acb3a08e5.png)

**Comment by benwoody** [comment]
:+1: last update was great as well!
