### ISSUE TITLE
Size Limit for Syntax Highlighter

### ISSUE THREAD

**Issue by naltatis** [dennisreimann/ioctocat#167]
I've noticed that i don't get highlighting for this file in the new code browser:

https://github.com/visionmedia/jade/blob/master/jade.js

Is this a size issue?

**Comment by dennisreimann** [comment]
Okay, I tracked it down but could not fix it. The problem isn't related to the size of the document, but some escape sequences like "/\/" in there… I'll need to dig deeper and see whether it's a html escaping error (I already tried some things there) or if it's a bug in the highlighting code. Somehow this problem does not occur with the jade.min.js …
