### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by jsvnm** [dennisreimann/ioctocat#177]
Original title and description:
### list all starred repos

have 199. didnt count, but ioctocat shows fewer.

**Comment by dennisreimann** [comment]
yep, right now it's the most 30 or 50 recent ones. I'll have to add paging for that.

**Comment by jsvnm** [comment]
sorting them by latest commit date would be very nice too

**Comment by dennisreimann** [comment]
That's actually how it is done right now, the first 30 starred repos, sorted by push date:
https://github.com/dennisreimann/ioctocat/blob/master/AppConstants.h#L84

I'll add paging, tehre are more areas of the app that need that functionality.
Can't give a date for that, but it will happen.

**Comment by pgrinchenko** [comment]
How do you see your starred repositories? I cannot see any. Please advise.

**Comment by dennisreimann** [comment]
In v1.7.0 the list of starred repos is at the bottom of the personal repos list. With v1.7.1 (should be out at the beginning of next week) this a separate list, you can access directly from the navigation menu.

**Comment by pgrinchenko** [comment]
Thank you for clarification.
