### ISSUE TITLE
Issues: Filter for owned issues

### ISSUE THREAD

**Issue by benjicx** [dennisreimann/ioctocat#179]
Sow issues that have been assigned to me.

**Comment by dennisreimann** [comment]
What in particular isn't right about the issues listed in the issues tab?

**Comment by benjicx** [comment]
I'm trying to find a way to show the issues that are assigned you me rather
than a list of all issues.

**Comment by dennisreimann** [comment]
I think this would be the `assigned` and `created` filter as described here: http://developer.github.com/v3/issues/#list-issues - right?

**Comment by benjicx** [comment]
Yep!
