### ISSUE TITLE
Option for relative date/times.

### ISSUE THREAD

**Issue by JakeWharton** [dennisreimann/ioctocat#18]
It would be nice to have a settings option to change the date/time to relative times (ex.: 4 hours ago) similar to how GitHub display the feeds on the site.

They seem to use:

< 1 minute = just now

< 1 hour = x minutes ago

< 1 day = x hours ago

Otherwise = x days ago

**Comment by intabulas** [comment]
latest commit to the master branch adds relative time code. The implementation is just in the My Feeds section so far. This right now is enabled and not toggleable, will add toggle to setting shortly

**Comment by intabulas** [comment]
housekeeping, closing this as its implemented
