### ISSUE TITLE
Pull Request Support

### ISSUE THREAD

**Issue by stephenway** [dennisreimann/ioctocat#180]
Show Pull Requests in timeline and make them viewable.

**Comment by dennisreimann** [comment]
In v1.6.3 (the current HEAD, soon to be released on the App Store) they are available from the timeline, but not from the repo page. I'll integrate them fully soon :)

**Comment by dennisreimann** [comment]
Most of the pull request integration is done now. What's still missing:
- Show changed files
- Show diffs
- Allow merging if the pull request can automatically be merged.

I'll add this during the next days :)

**Comment by stephenway** [comment]
Thanks for working on this @dennisreimann!
Another thing that just got added recently, once merged the topic branch can be deleted.

**Comment by dennisreimann** [comment]
I saw that announcement on the blog, the API docs don't state anything about that yet. I'll talk to GitHub how this will work for pull requests that get merged via API. Thanks for the pointer.

**Comment by dennisreimann** [comment]
Okay, automatic cleanup via API isn't supported yet, but we can make another [call to delete the branch](http://developer.github.com/v3/git/refs/#delete-a-reference).

**Comment by stephenway** [comment]
Awesome!
