### ISSUE TITLE
Going back to the account selection page and re-selecting an account crashes the app

### ISSUE THREAD

**Issue by aharren** [dennisreimann/ioctocat#183]
since switching to ARC

**Comment by cvx** [comment]
"Cannot remove an observer `<MyEventsController 0x1d5f8610>` for the key path "loadingStatus" from `<GHEvents 0x1d5d2a70>` because it is not registered as an observer."

**Comment by aharren** [comment]
Same here:

**\* Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <MyEventsController 0x1d572b30> for the key path "loadingStatus" from <GHEvents 0x1d5608c0> because it is not registered as an observer.'

**Comment by aharren** [comment]
stack trace (compressed):

```
-[EventsController dealloc] + 70 at EventsController.m:54
-[MyEventsController dealloc] + 466 at MyEventsController.m:98
-[AccountController .cxx_destruct] + 122 at AccountController.m:19
-[UIViewController dealloc]
_CFAutoreleasePoolPop
__CFRunLoopRun
```
