### ISSUE TITLE
highlight new events without leaving account

### ISSUE THREAD

**Issue by jerodsanto** [dennisreimann/ioctocat#184]
I love how new events since my last refresh are highlighted by that blue background!

However, this does not happen if I stay on the feed view and just refresh the feed. I have to go out of my account and come back in to trigger the highlighting.

Feature or bug? Either way, I'd love to see this interaction adjusted.

Great app, thanks!

**Comment by dennisreimann** [comment]
Good catch, will fix that in the next release (which will be out early January).
