### ISSUE TITLE
Feed view shows up and disappears again after launching

### ISSUE THREAD

**Issue by aharren** [dennisreimann/ioctocat#185]
git-hash of tested version: 343ae9df6a9c0a2992ccfb6167b784e6a56e7f6d

steps to reproduce:
1. leave iOctocat, e.g. switch to springboard
2. kill the running iOctocat instance
3. launch iOctocat again
4. the feed view shows up and directly disappears again, see screenshot below

![screenshot](https://f.cloud.github.com/assets/175273/15777/b0f59d06-47c6-11e2-9135-53d16cdff0cd.png)

**Comment by dennisreimann** [comment]
I've seen that too but could not reproduce it with the current master. I'll have to dig deeper into that :)

**Comment by aharren** [comment]
Right, current master doesn't seem to have this problem.

**Comment by dennisreimann** [comment]
Hmm, I'm not sure whether or not the problem is gone, because I didn't change anything that could have fixed it. I'll send out the beta later today and we'll see from the feedback if it still occurs. I've seen that myself but could not reproduce it during the last few days.

**Comment by dennisreimann** [comment]
Seems to be gone, will reopen this in case it reappears.
