### ISSUE TITLE
Touching the status bar no longer scrolls to the top of a feed

### ISSUE THREAD

**Issue by aharren** [dennisreimann/ioctocat#186]
git-hash of tested version: 343ae9df6a9c0a2992ccfb6167b784e6a56e7f6d

steps to reproduce:
1. select the user's news feed
2. scroll down
3. touch the status bar
4. the view doesn't scroll to the top of the feed

**Comment by dennisreimann** [comment]
That might be related to the [changes I've made to ECSlidingViewController](https://github.com/iOctocat/ECSlidingViewController/commit/c4831098b9725073e43d5d5339afde17d0faed87) or even the whole ECSlidingViewController integration. I'll investigate.

**Comment by klaustopher** [comment]
Should be relatively simple

```
[currentView setScrollsToTop:YES];
```

**Comment by dennisreimann** [comment]
But isn't that supposed to work automagically? It did before if I remember correctly.
