### ISSUE TITLE
Organization Events: Loading error

### ISSUE THREAD

**Issue by aronwoost** [dennisreimann/ioctocat#193]

**Comment by dennisreimann** [comment]
For my organizations it seems to work. Which org is causing problems for you? (and which version are you using?)

**Comment by aronwoost** [comment]
Organization: MOLIS, version: 1.6.7

**Comment by dennisreimann** [comment]
Hmm, that works for me too, can you debug it in Xcode and send the log?

**Comment by aronwoost** [comment]
Ähmm, how do I do that? :)

**Comment by dennisreimann** [comment]
It's described in the README https://github.com/dennisreimann/ioctocat#building-and-debugging

Let me know when you need help.

**Comment by dennisreimann** [comment]
Does this still occur?

**Comment by aronwoost** [comment]
It does. Also with 1.7.1. Haven't found time to build. Will do in the next days.

**Comment by dennisreimann** [comment]
Hey Aron, did you find the time to debug this?

**Comment by aronwoost** [comment]
Not yet (sry). I got a new device (replacement). Can you kick of a new build for me?

**Comment by dennisreimann** [comment]
I'll release a new beta during the next days, have a nice weekend!

**Comment by klaustopher** [comment]
btw: I also got a replacement, put my new UDID into hockey

**Comment by dennisreimann** [comment]
Aron, another idea: Can you invite me to the MOLIS organization just so that I can debug this?

I can load the public activities feed just fine, don't know what can be wrong with the private feed :(

**Comment by aronwoost** [comment]
done

**Comment by aronwoost** [comment]
Issue disappeared after re-authentication.
