### ISSUE TITLE
Design: Menu should be darkened

### ISSUE THREAD

**Issue by danielgrippi** [dennisreimann/ioctocat#197]
As a regular user of Gmail and Facebook for iOS, it seems to me that the pull out menu on ioctocat should be of a dark color scheme if we are to follow this new mobile UX paradigm.

**Comment by dennisreimann** [comment]
Hehe, you are not alone with that wish, so this might come soon :)

**Comment by danielgrippi** [comment]
Yay!  :)

**Comment by dennisreimann** [comment]
This is what it will look like soon (v.1.7.1 is submitted):

![iOS Simulator Bildschirmfoto 07 01 2013 23 41 16](https://f.cloud.github.com/assets/886/48765/f3cf61ce-591f-11e2-8baa-ed0e92fc9346.png)
