### ISSUE TITLE
Crash in v0.8.7 on initial start

### ISSUE THREAD

**Issue by eric** [dennisreimann/ioctocat#20]
When running v0.8.7 for the first time without having the authentication settings set, the app crashes immediately on startup.

I found that I had to enter the username and API key manually to get it to work.

**Comment by dennisreimann** [comment]
Oops, my fault. A fixed version can be downloaded here:
http://dennisbloete.de/projects/ioctocat/iOctocat-v0.8.7.1-AdHoc.zip

**Comment by dennisreimann** [comment]
Bugfix for initial start. Closed by 8aa73161cd17484cb3bed144a516d5d6e066297b
