### ISSUE TITLE
Issues: Support labels

### ISSUE THREAD

**Issue by robrohan** [dennisreimann/ioctocat#200]
Personally, I need labels in issues or the issues part of the app isn't useful.  We have a bunch of predefined labels that I need to add to issues. (for me that's the main reason I downloaded this app)

Perhaps it is there and I can't find it, but it appears that the label portion of issues isn't represented in the app.

**Comment by dennisreimann** [comment]
Thanks, better issue management and notification support will be the main part of v1.8.0.

**Comment by robrohan** [comment]
win
