### ISSUE TITLE
Open repository files in iOS application of choice

### ISSUE THREAD

**Issue by NichUK** [dennisreimann/ioctocat#205]
It would be very useful to allow repository files to be opened in an external application of the users choice in a way similar to that of Dropbox, and most other file selection apps.

This would allow file types other than those directly supported by ioctocat to be viewed (and maybe one day edited ;) )

**Comment by klaustopher** [comment]
Editing would be awesome but since there is almost no way to get the file from an external application back into iOctocat :frowning:

But I agree, opening in external apps would be good ;)
