### ISSUE TITLE
line numbers in code view

### ISSUE THREAD

**Issue by NichUK** [dennisreimann/ioctocat#207]
Would be really useful when trying to look at code after receiving an exception report!

**Comment by dennisreimann** [comment]
you can activate line numbers in the settings.app (just like switching the theme for the code view)

**Comment by NichUK** [comment]
Sorry, I don't understand that... I can't find any button or menu item which lets me at settings at all

**Comment by novabyte** [comment]
NichUK Go into Settings (the iOS configuration application), scroll down to `iOctocat` and click the toggle button next to the "Line Numbers" option:

![photo](https://f.cloud.github.com/assets/229752/59715/d0ea2668-5bdf-11e2-977c-2942aca56fd8.PNG)

**Comment by NichUK** [comment]
Oh... OK... Suitably embarrased now. :-) I never thought of looking there! Thanks Chris! :-)
