### ISSUE TITLE
Events: Follower button doesn't work

### ISSUE THREAD

**Issue by stephenway** [dennisreimann/ioctocat#209]
If a user follows you and that action shows up in the news feed, the first button on the left doesn't do anything. Also I find it confusing that there are multiple buttons that have the same icon and no context as to what user.

**Comment by dennisreimann** [comment]
Thanks for reporting this bug.

> Also I find it confusing that there are multiple buttons that have the same icon and no context as to what user.

I agree with you on that and I talked to some more people who find it confusing. The buttons will be taken out when I find the time to rewrite some code and get to link the actual text, like on GitHub.com. This way one wouldn't even have to expand the event to show the details and buttons.

**Comment by stephenway** [comment]
Agreed, thanks!
