### ISSUE TITLE
Unsupported URL

### ISSUE THREAD

**Issue by jk** [dennisreimann/ioctocat#21]
Hi,

in the user profile detail view I get an error when I'm clicking on mail adresses: »Unsupported URL\nThis URL wasn't loaded: mailto:?to=@«

But perhaps this is only related to the simulator, cuz there's no Mail.app.

![Screenshot](http://img.skitch.com/20090505-ksp7bfd1jpfa79hmc4we7s97d9.jpg)

**Comment by intabulas** [comment]
initWithFormat had the %@ reversed, fixed in 08176920

**Comment by dennisreimann** [comment]
verified this is working on the device
