### ISSUE TITLE
Adjusted icon

### ISSUE THREAD

**Issue by reynaert1250** [dennisreimann/ioctocat#210]
Hi all,

I saw the adjusted icon design and it's kinda bad. I just pulled the source files from my backup and will create a new version. I will post a pull request this week.

Best, 
Roy

**Comment by dennisreimann** [comment]
Hey Roy, I'm sorry that you do not like the current one. Nevertheless, please don't put any effort into creating a new one. I settled on this one and don't want to change the icon every other version.

**Comment by reynaert1250** [comment]
Hey Dennis, 

I already finished the revamp so i thought, let's post this thingy. I understand that you don't want to change the icon every version. This is just a cleaner revamp with more details. If you like it i will make a pull request.

![iOctocat_revamp](https://f.cloud.github.com/assets/773549/69388/82bdf548-5f5c-11e2-92a7-add091de6ad2.jpg)

**Comment by klaustopher** [comment]
:thumbsup:
