### ISSUE TITLE
Repository View: Icon position

### ISSUE THREAD

**Issue by nonuts** [dennisreimann/ioctocat#211]
Maybe the icon in repo view could sit in front of the repo name. now, being on the right side, it could be confused as functionality/a button. Also, that way the repo name would align nicer w the list view beneath

**Comment by nonuts** [comment]
Also, stats under name could use icons instead of 'forks'/'stars'

**Comment by dennisreimann** [comment]
Agreed. I'd like to redesign the profile views and some more list views of the whole app, because this grouped table view style layout feels dated too. All of this will find it's way into v2.0
