### ISSUE TITLE
'Feeds' label redundant

### ISSUE THREAD

**Issue by nonuts** [dennisreimann/ioctocat#213]
In the table view, or can there be more than one feed? Maybe a simple line as a delimiter to the notifications would do the job, too.

**Comment by dennisreimann** [comment]
The feeds section can also contain organizations, in case you are member of at least one organization.

![iOS Simulator Bildschirmfoto 15 01 2013 23 00 09](https://f.cloud.github.com/assets/886/69483/0a7fe25a-5f5f-11e2-9a06-a09e70f81101.png)
