### ISSUE TITLE
Notifications: Push for GitHub notifications

### ISSUE THREAD

**Issue by ichina** [dennisreimann/ioctocat#214]
- [x] Server: Setup certificates for sending push notifications
- [x] Server: Setup for registering devices and accounts
- [x] App: Register devices and accounts at the server backend
- [x] Server: Setup a queue for the polling jobs
- [x] Server: Job for polling GitHub notifications for a specific account
- [x] Server: Cronjob for adding polling jobs to the queue
- [x] Server: Push payload
- [x] App: Handle received push notification
- [x] App: Handle received push notification while the app is in foreground

**Comment by dennisreimann** [comment]
It's already in the making, see https://twitter.com/iOctocat/status/291195591856361472
