### ISSUE TITLE
unable to edit codes

### ISSUE THREAD

**Issue by lin-toto** [dennisreimann/ioctocat#216]
I'm unable to edit codes.

**Comment by dennisreimann** [comment]
Yep, that's right, but I won't implement anything like that, because that's not the focus of the app.

**Comment by lin-toto** [comment]
Why not that makes the app much better

**Comment by dennisreimann** [comment]
well, you could go ahead and fork the app to make it support text editing and git.

**Comment by lin-toto** [comment]
And the app becomes more useful if u add it. People like me want to edit codes with their iDevices.

**Comment by dennisreimann** [comment]
Here you go:

https://itunes.apple.com/de/app/textastic-code-editor/id383577124?mt=8
https://itunes.apple.com/de/app/textastic-code-editor-fur/id550156166?mt=8

**Comment by klaustopher** [comment]
I thought about making something like that but there are a bunch of problems ... 
- There is no open source text editor view that supports syntax highlighting
- You cannot clone a git repo to an iDevice
- Adding files and commit through the GitHub API is far from being straight forward. [See here](http://swanson.github.com/blog/2011/07/23/digging-around-the-github-api-take-2.html)
- If somebody else makes changes between you starting to edit the file and making the commit through the API, you might end up creating conflicts that cannot be merged.

And the biggest issue is, that unless you do some simple HTML and JavaScript manipulation, there is NO WAY to run any of your code on an iDevice. So, you are unable to test your code before you commit. I know, that there is Travis and maybe some internal Continuous Integration solutions that run the test for you but I don't think that this replaces testing on your own machine BEFORE commiting and pushing

**Comment by lin-toto** [comment]
Ok, thanks for the reply. I understand why you don't want to add an editor now. The app is still great!
Btw I do html and js dev lol

**Comment by cvx** [comment]
@klaustopher 
1. what about textmate and web-based code editors (e.g. cloud9)?
2. is there any iOS limitation that prevents it?

Such feature could be used to edit wiki/readme/docs, these do not require complete development environment. :smile: 

That being said, I think that amount of work required to implement such feature outweighs any benefits of having it in the app.

**Comment by klaustopher** [comment]
Textmate would be an option, I don't know how easy it would be to extract their editor component and convert it to a CocoaTouch view. [ACE](https://github.com/ajaxorg/ace), the editor used by cloud9, works barely in the mobile Safari, have you tried using it in a UIWebView that does not use the optimized JS engine? I'd suggest you don't :smile: 

AFAIK, you don't get any access to the FileSystem directly so there would be no chance to init a repository using libgit2... Furthermore [libgit2/objective-git](http://github.com/libgit2/objective-git) doesn't support fetch, pull or clone right now.

I agree that the amount of work absolutely outweighs the benefits ... But it would be soooo cool, to edit my stuff on the iPad, scp it to a test system, try it and make a commit ;) Now I have to use prompt to access my servers and work there ;)

**Comment by lin-toto** [comment]
Isn't there an API to edit things on github? I can edit stuffs using the web

**Comment by klaustopher** [comment]
The problem is, that you have to make a commit... I posted a link that describes how to do a commit through the GitHub API. It is possible, but there are still the other problems I described above. As Dennis said: Its not the focus of the app. And I agree with CvX: It would be an awesome feature, but the time it takes to implement totally outweighs the benefit

**Comment by dennisreimann** [comment]
Let's keep it like this: The app has become complex enough, so that I can barely handle implementing new features, being available for support and fixing bugs myself - besides my day job. I won't implement code editing, because it is a) a really big topic, 
b) not the focus of the app and
c) there are good editors out there.
