### ISSUE TITLE
header toolbar explicit color?

### ISSUE THREAD

**Issue by JakeWharton** [dennisreimann/ioctocat#22]
I have a jailbroken iPhone and use a Winterboard extension which turns all of the header toolbars black rather than Apple's blue. For applications that set an explicit color for the background (like TwitterFon's blue/yellow/etc.) it does not override the color. iOctocat, however, has the default color for the background yet the extension does not turn it black. I poked around the xib's but didn't see anything that jumped out.

It's not really a big deal, feel free to close this issue if in 5 minutes you can't figure it out. I just like the black look better but don't want to force it on everyone just to get it nor do I think Apple should really force the blue.

**Comment by dennisreimann** [comment]
Hmm, didn't find anything either.
