### ISSUE TITLE
Fix NSInvalidArgumentException in - [EventsController tableView:didSelectRowAtIndexPath:], line 154

### ISSUE THREAD

**Issue by dennisreimann** [dennisreimann/ioctocat#222]
## Stacktrace

<pre>EventsController;tableView:didSelectRowAtIndexPath:;EventsController.m;154
-;start;;</pre>

## Reason

**\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UITableViewCell markAsRead]: unrecognized selector sent to instance 0x1fa1f1b0'
## Link to HockeyApp
- [https://rink.hockeyapp.net/manage/apps/19419/app_versions/2/crash_reasons/2222468](https://rink.hockeyapp.net/manage/apps/19419/app_versions/2/crash_reasons/2222468)

**Comment by pokedit** [comment]
Bggg
