### ISSUE TITLE
Markdown support for issue comments and md files in repositories

### ISSUE THREAD

**Issue by driesvints** [dennisreimann/ioctocat#225]
Perhaps stating the obvious but markdown support for issue comments would be very cool. I don't know if this was requested in a previous issue or not. I didn't find any. 

Also would be nice if markdown files in repos showed the markdown rendered version first and then a button to view the raw version if you want to. Github does this by default.

**Comment by dennisreimann** [comment]
Thanks for creating an issue for that, its on my personal TODO for quite a while now as there are several places where this'd be useful.

**Comment by dennisreimann** [comment]
I'm going to reduce this to markdown rendering in comments and keep track of the other feature in #375
