### ISSUE TITLE
GFM Task List Support

### ISSUE THREAD

**Issue by nicolai86** [dennisreimann/ioctocat#226]
Hey!

Since github introduced [Task Lists](https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments) I became a huge fan of them because they ease coordination of open tasks in a PR extremly.

Any chances that iOctocat gets support for these Markdown managed task lists?

**Comment by dennisreimann** [comment]
Since its just markdown, it already works, see #189 :)

**Comment by nicolai86** [comment]
yay! thanks! :)
