### ISSUE TITLE
commits

### ISSUE THREAD

**Issue by jefmwols** [dennisreimann/ioctocat#228]
Is there a way to view a list of commits?

**Comment by dennisreimann** [comment]
Not yet, but it's on my internal TODO. Basically there's everything in place to make it work, but I'll have to add pagination for the commits list too, which I still have to figure out. Will happen definitely :)

**Comment by dennisreimann** [comment]
Okay, they are on master now and will be part of v1.7.6 which I want to release tomorrow. Right now there's just the 30 latest commits, but I'll add pagination to it in the future.
