### ISSUE TITLE
Removing someone from my "Following" list causes the UI to become of by one

### ISSUE THREAD

**Issue by brndnblck** [dennisreimann/ioctocat#229]
Open your following list, then stop following someone. 

The UI will now be out of sync and every user (n) after will show data from the following user (n+1).

There's not need to talk to the server again, but the list and the UI should be refresh in memory to reflect the change.

**Comment by brndnblck** [comment]
The same problem exists for most other lists: watched, starred, etc

**Comment by dennisreimann** [comment]
Good point, I'll fix that in v1.7.6

**Comment by brndnblck** [comment]
Thanks ;-)
