### ISSUE TITLE
closing tickets from non admin organization

### ISSUE THREAD

**Issue by CyrilPeponnet** [dennisreimann/ioctocat#232]
Hi, I am contributor to an organization repo, I have all the rights except admin. 

In ioctocat, I can't close issues I can only add comments. It's working fine from web interface btw. Am I missing something ?

Thanks

**Comment by dennisreimann** [comment]
No, you are right. This has been fixed two days ago (see 7d05ddd0) and will be part of the v1.7.6 release which I'll submit today :)

**Comment by CyrilPeponnet** [comment]
Cool :) thanks for fast answer ! I buy it yesterday there was a price drop :)
