### ISSUE TITLE
twitter integration

### ISSUE THREAD

**Issue by elvisimprsntr** [dennisreimann/ioctocat#233]
I want to twitter to followers on recent updates to my repos.  For example send a link to the repo.

**Comment by dennisreimann** [comment]
I'll add something like "copy repository URL" and let everyone decide how to share it. I won't do Twitter integration for iOctocat, because it's out of scope, sorry.

**Comment by ruddfawcett** [comment]
Just a question, and this may seem like a stupid question, but why iOctocat?

**Comment by elvisimprsntr** [comment]
The name?   Long story, but Octocat is the official mascot for GitHub which the founders have a picture of in their conference room/lounge at their offices.  Kind of like an velvet Elvis painting or painting of dogs playing poker.   Or so I have read.
