### ISSUE TITLE
Why was the highlight removed from the cells to indicate unread items?

### ISSUE THREAD

**Issue by iosdeveloper** [dennisreimann/ioctocat#234]
I noticed it got removed in the latest update available on the App Store.

**Comment by dennisreimann** [comment]
I didn't remove it, when does this occur for you?

**Comment by iosdeveloper** [comment]
New items just do not have the light blue highlight.

**Comment by dennisreimann** [comment]
Which version are you using? The one from the App Store or the current master? If the current master: Could it be that you are using your email address as login?

**Comment by iosdeveloper** [comment]
v1.7.5 from the App Store. Username as login.

**Comment by dennisreimann** [comment]
k, I'll investigate some more and will hopefully find it, so that I can integrate a fix in v1.7.6 which I plan to release later today.
