### ISSUE TITLE
Feature request : random search

### ISSUE THREAD

**Issue by didbre** [dennisreimann/ioctocat#235]
Being able to launch a random search.

**Comment by dennisreimann** [comment]
Could you describe what you mean exactly? Sorry, I don't get it.

**Comment by didbre** [comment]
This is clearly an request that falls within the domain : fun only.  By random search, I mean being able to randomly browse repository.  Maybe a simple version of this : http://shout.setfive.com/2012/08/14/fun-stuff-github-random-repository-browser/

**Comment by dennisreimann** [comment]
K, got it :)

Maybe as an easteregg in v2.0? :)

**Comment by didbre** [comment]
Thanks! At least there hope this killer feature that will change the world forever will, probably, be include ioctocat 2.0 :)
