### ISSUE TITLE
Feature Request: URL Schemes

### ISSUE THREAD

**Issue by ruddfawcett** [dennisreimann/ioctocat#236]
Hello, haven't really poked around in the code, but I was wondering if there were any URL schemes for iOctocat? Something like iocto://user/username?  Or iocto://repo/repo?  That would be awesome.  Again, sorry if there is already URL scheme integration, or if this topic has already been brought up.  Thanks!

**Comment by dennisreimann** [comment]
Use ioc:// :)

**Comment by dennisreimann** [comment]
But it is the full github.com URL, like ioc://github.com/dennisreimann/ioctocat - this way you can open links that you receive via Twitter or so just by changing the protocol.

**Comment by ruddfawcett** [comment]
Sweet!  Thanks!
