### ISSUE TITLE
private repo's not showing in user profile on device

### ISSUE THREAD

**Issue by intabulas** [dennisreimann/ioctocat#24]
tracking issue:

private repo's not showing in user profile on device but show in the simulator. They do properly show on the My Repositories tab, just not when you view your own profile

**Comment by dennisreimann** [comment]
@intabulas: Is this fixed by your addition of "authenticatedRequestForUrl" ?

**Comment by intabulas** [comment]
no it doesnt fix this

**Comment by dennisreimann** [comment]
I guess I have fixed it, but I can't verify it, because I don't have a paid plan... can someone else test this?

**Comment by intabulas** [comment]
verified fixed

**Comment by intabulas** [comment]


**Comment by intabulas** [comment]


**Comment by intabulas** [comment]
