### ISSUE TITLE
Remove SVPullToRefresh

### ISSUE THREAD

**Issue by iosdeveloper** [dennisreimann/ioctocat#244]
Implement UIRefreshControl / ODRefreshControl (iOS 5) instead

**Comment by dennisreimann** [comment]
Could you explain this a little better? What would be the benefits?

**Comment by iosdeveloper** [comment]
Adapting the system standard. In iOS 6 all pre-installed apps implement UIRefreshControl for refreshing content.

**Comment by dennisreimann** [comment]
I'll do this, when iOS 7 is out. My policy is to support the latest two OS versions, and because this is available from iOS 6 on, I can't integrate it right now.

**Comment by dennisreimann** [comment]
I had a look at the UIRefreshControl API and it is very simple and basic. I haven't totally decided yet but can imagine that we will stick with SVPullToRefresh, just because it is more flexible and also brings infinite scrolling, which will come in handy when integrating pagination.

**Comment by dennisreimann** [comment]
Closing, we'll keep SVPullToRefresh.
