### ISSUE TITLE
Comment cell text disappears

### ISSUE THREAD

**Issue by iosdeveloper** [dennisreimann/ioctocat#245]
Open an issue with a lot of comments.
Some cells might not even display text once, some texts might disappear when scrolling, some cells will behave as expected.
When an item is (re-)loaded, the behavior might change.

**Comment by dennisreimann** [comment]
Duplicate of #187

**Comment by iosdeveloper** [comment]
Is this actually a duplicate? This is about text disappearing in general (which obviously is a bug that should be fixed. Waiting for markdown implementation is not an option.), whereas #187 is about links.

**Comment by dennisreimann** [comment]
I'll be refactoring the whole approach of rendering comments etc. because I want to show the rendered Markdown, not the raw output. 

I'm tracking the state in the other issue, that's why I closed this one. 

Am 09.02.2013 um 23:14 schrieb iosdeveloper notifications@github.com:
