### ISSUE TITLE
Enlarge text view

### ISSUE THREAD

**Issue by iosdeveloper** [dennisreimann/ioctocat#246]
There is still some space left to the keyboard for the text view for new / edit issue.
Increasing the height would certainly help to have more than four lines visible at once without scrolling.

**Comment by iosdeveloper** [comment]
Maybe keep the previous smaller height in landscape orientation?

**Comment by dennisreimann** [comment]
We should adapt to whatever space is there.

**Comment by iosdeveloper** [comment]
#320 took over this issue. Closing...
