### ISSUE TITLE
Consistent behaviors

### ISSUE THREAD

**Issue by maxbaeumle** [dennisreimann/ioctocat#248]
Some views still implement a button instead of pull to refresh. Some views have the 'Show on GitHub' action, some do not.

**Comment by dennisreimann** [comment]
I think Pull to Refresh makes sense for notifications and events, the other data list aren't the same in my opinion. What do you think?

**Comment by iosdeveloper** [comment]
Sounds reasonable.

What about 'Show on GitHub'? It is available for organization profiles but not for personal profiles.

**Comment by dennisreimann** [comment]
Yep, I'll fix that. Will also add the option to copy the GitHub URL as I often find myself wanting to share that somehow.

**Comment by iosdeveloper** [comment]
That would be a great addition. Thanks!
