### ISSUE TITLE
Website Title? (In nav bar)

### ISSUE THREAD

**Issue by ruddfawcett** [dennisreimann/ioctocat#249]
I will form and add this when I get a chance, but just an idea to add the title of the website when you click on a users blog or projects website. Just adding the website's <title></title> as the Navigation Bar's title.

**Comment by dennisreimann** [comment]
yep, good point.

**Comment by dennisreimann** [comment]
Closed with 3aae10fea35b334465242cfc1f1aa85a58d58ba5
