### ISSUE TITLE
Accounts: Cache user gravatars

### ISSUE THREAD

**Issue by ruddfawcett** [dennisreimann/ioctocat#255]
It would be nice if the app would cache the user's gravatar and showed it in the accounts view instead of the default github icon...

**Comment by iosdeveloper** [comment]
Doesn't it do so when you first sign in?

**Comment by ruddfawcett** [comment]
Not for me?

**Comment by dennisreimann** [comment]
Yep, that's something that was there, but got lost when we started to clear the user cache when you go back to the accounts view. The avatars get cached, I'll habe to think about a solution for the accounts list. Thanks for bringing that up.

**Comment by ruddfawcett** [comment]
I just deleted my account and resigned in and when I went back to the accounts page, the avatar is there.  Weird.
