### ISSUE TITLE
Do not clear search field when selecting a different segment

### ISSUE THREAD

**Issue by iosdeveloper** [dennisreimann/ioctocat#256]
I often find myself entering a text and then switching from 'User' to 'Repository'. Unfortunately the search field is cleared.

You should not maintain two sets of data. The `UISegmentedControl` should only be used for performing a search, not for switching between the two sets of data.

**Comment by iosdeveloper** [comment]
Keeping this open as a feature request (only use the `UISegmentedControl` for performing a search, not for switching between the two sets of data (do not maintain two sets of data at all)).

**Comment by dennisreimann** [comment]
:+1:
