### ISSUE TITLE
Profile editing

### ISSUE THREAD

**Issue by elvisimprsntr** [dennisreimann/ioctocat#257]
Add ability to edit ones profile.

**Comment by dennisreimann** [comment]
Do you think this is needed as a feature when you are on the road?

**Comment by ruddfawcett** [comment]
It would be nice to add an explore view with a segmented controller, day, week, month

**Comment by elvisimprsntr** [comment]
I am on road and wanted to edit my profile via my cell phone.   No worries, i opened up my profile via the web and made the edit there.   It's a low use feature, so I wouldn't be upset if it didn't make it.

**Comment by dennisreimann** [comment]
I'm gonna close this, please reopen if someone would like to contribute this feature.
