### ISSUE TITLE
Buttons do not layout / size correctly

### ISSUE THREAD

**Issue by iosdeveloper** [dennisreimann/ioctocat#264]
Screenshots:
![image](https://f.cloud.github.com/assets/655921/168488/e651ba70-79fd-11e2-947f-ba160bc1b933.jpg)
![image](https://f.cloud.github.com/assets/655921/168487/e5961388-79fd-11e2-8653-4d36174d7495.jpg)

**Comment by ruddfawcett** [comment]
Oh yes... I noticed this too.

**Comment by dennisreimann** [comment]
Unfortunately this is hard to reproduce, but I hope I fixed it with the mentioned commit.

**Comment by dennisreimann** [comment]
Okay, it still occurs and can be reproduced by posting a new comment. After that, the Add comment button is too large.

**Comment by iosdeveloper** [comment]
Still occurs, like #301. Reopening...

**Comment by dennisreimann** [comment]
Don't dare to reopen, @iosdeveloper :tongue:
