### ISSUE TITLE
Organization feed

### ISSUE THREAD

**Issue by iosdeveloper** [dennisreimann/ioctocat#265]
The first two buttons in the expanded row on the screenshot both perform the same action (they open the organization's profile). Intended behavior?
![image](https://f.cloud.github.com/assets/655921/168508/9b17e45c-79fe-11e2-97cd-08a23c45baa0.jpg)

**Comment by dennisreimann** [comment]
This will be fixed when I remove the buttons and link the text, there's already an issue for that - tracking the progress there.
