### ISSUE TITLE
Feature Request:  "limit loader"

### ISSUE THREAD

**Issue by ruddfawcett** [dennisreimann/ioctocat#266]
Not sure how to title this, but it would be nice if when you got to the bottom of a UITableView, it loaded the next 25 or however many items, similar to facebook?

**Comment by iosdeveloper** [comment]
Duplicate of #177. Same happened to me a few days ago.

**Comment by ruddfawcett** [comment]
Ahhh

**Comment by dennisreimann** [comment]
:+1:
