### ISSUE TITLE
Issues: Don't scroll the table view to the top when going back from an issue

### ISSUE THREAD

**Issue by iosdeveloper** [dennisreimann/ioctocat#269]

**Comment by dennisreimann** [comment]
I don't think that this is happening on the current master - can you check whether or not it works for you?

**Comment by dennisreimann** [comment]
@iosdeveloper did you check if this is working again on current master?

**Comment by iosdeveloper** [comment]
Issue can still be reproduced. I scroll through the issues, open an issue and go back. The table view scrolls to the top and I loose my offset.

**Comment by dennisreimann** [comment]
Ah, now I get it. I just read "reload" and thought the app would fetch new issue data from the API. That should be easy to fix :)
