### ISSUE TITLE
Notifications: "Read all" should be more sensible

### ISSUE THREAD

**Issue by koraktor** [dennisreimann/ioctocat#278]
Currently, marking all notifications as read will cause (suprise) all notifications as read. This isn't that good, when you have more than 50 notifications. iOctocat won't show more than 50 notifications at once, so you will lose notifications you weren't even aware of.

Two suggestions for this problem:
1. Remove only those notifications that are visible at the moment (I guess this is problematic due to API limitations, i.e. it will require several requests)
2. Provide additional UI elements that mimic GitHub's own UI, i.e.:
   - show how many notifications are available overall
   - show how many notifications are available per repository
   - allow to mark a repository as read

**Comment by dennisreimann** [comment]
I saw that one coming as I'm currently running into it myself, while testing the notifications. I have to think about it and test the limit of the maximum number of notifications that can be loaded.

One thing I'd like to add anyways is the possibility to mark all notification for a specific repo as read, as you already mentioned.

**Comment by iosdeveloper** [comment]
Is the first suggestion (marking only visible notifications as read) available via the API or not?

**Comment by dennisreimann** [comment]
Well, we'd have to call the API once for every visible notification, because there is no way to submit a list of IDs.

**Comment by dennisreimann** [comment]
btw: I checked and there's a limit of 50 items we can fetch at once (without pagination).

**Comment by dennisreimann** [comment]
Currently I'd tend to disable the Mark all as Read button in case there are 50 items (the maximum) after loading the notifications. What do you think?

Sending a request per notification is some kind of overkill imho.

**Comment by dennisreimann** [comment]
@koraktor @iosdeveloper any thoughts on disabling the button in case the maximum amount of notificatins is loaded? I'd like to close this for v1.7.8
