### ISSUE TITLE
Repository: Language breakdown

### ISSUE THREAD

**Issue by ruddfawcett** [dennisreimann/ioctocat#279]
Just a little bar with the percentages of the different languages used in a repo...

**Comment by ruddfawcett** [comment]
Wow... Didn't even think of that aspect haha...

**Comment by dennisreimann** [comment]
There is an [API endpoint for that](http://developer.github.com/v3/repos/#list-languages). It's ine of those features that I don't really need myself, but if someone is willing to add it I'd pull it in. Don't get me wring, I just don't want the app to be more complex than it already is.

**Comment by ruddfawcett** [comment]
I think I'll add it if I have time then send a pull...

**Comment by dennisreimann** [comment]
Awesome :godmode:

**Comment by iosdeveloper** [comment]
You could just add the major language below the repository's title (next to star, forks).

**Comment by dennisreimann** [comment]
Why has this been closed?

**Comment by ruddfawcett** [comment]
Whoops... Sorry, didn't mean to do that.  Now this is something a little easier that I think I can add...

**Comment by iosdeveloper** [comment]
Closed by ddb9436b
