### ISSUE TITLE
'No comments' slightly offset

### ISSUE THREAD

**Issue by iosdeveloper** [dennisreimann/ioctocat#283]
Screenshot:
![image](https://f.cloud.github.com/assets/655921/173641/23a4d368-7ae3-11e2-9fb5-248d40a7d87e.jpg)

**Comment by ruddfawcett** [comment]
Nit picky much? Haha just kidding

**Comment by iosdeveloper** [comment]
I'm the evil issue bot keeping @dennisreimann from making any progress on push!! MUHAHAHA!!!!

**Comment by ruddfawcett** [comment]
That reminds me... @username parsing?  Link to users page?  Possible future feature? @iosdeveloper

**Comment by iosdeveloper** [comment]
Nice try... Duplicate of #225 ;)

**Comment by ruddfawcett** [comment]
Issue number parsing then? @iosdeveloper

**Comment by ruddfawcett** [comment]
Or username auto completes when you start typing @username based on users in issue @iosdeveloper

**Comment by iosdeveloper** [comment]
I have so many more feature req's I'm currently holding back so that @dennisreimann can breathe and continue his work on push.

**Comment by ruddfawcett** [comment]
Oh ok lol... If he just used a service, it might be a little easier....

**Comment by iosdeveloper** [comment]
Pushing the notifications to devices is only a very little part of what is actually happening behind the scenes (from managing the app badge with multiple GitHub accounts per device token to polling the API with respect to rate limits). A service would not solve these specific problems that currently cause @dennisreimann headaches and sleepless nights (I'm just kidding but you get the idea).

**Comment by ruddfawcett** [comment]
Oh ya, no, I understand.

**Comment by dennisreimann** [comment]
You guys rock :boom:

**Comment by iosdeveloper** [comment]
I can still reproduce this with the current master.
Screenshot:
![image](https://f.cloud.github.com/assets/655921/179480/6882684c-7c00-11e2-8c3c-479b505606b7.jpg)

**Comment by dennisreimann** [comment]
Hmmmmm

**Comment by dennisreimann** [comment]
Seems to happen when the comments pop in after the repo has been loaded. Investigating ;)
