### ISSUE TITLE
Repository: Sticky header

### ISSUE THREAD

**Issue by ruddfawcett** [dennisreimann/ioctocat#285]
Was wondering if it would be possible to have the user/repo header (the one containing star/fork count) could be sticky, and the tableview would scroll under it?  Just an idea...

**Comment by iosdeveloper** [comment]
I like the idea!

**Comment by dennisreimann** [comment]
Contribution welcome :)

**Comment by dennisreimann** [comment]
Why has this been closed?

**Comment by ruddfawcett** [comment]
Oh... I was going to work on this and then send a pull request.  I'll reopen it.

**Comment by dennisreimann** [comment]
Anyone still interested in that?
