### ISSUE TITLE
Issues: Milestones

### ISSUE THREAD

**Issue by jelledelaender** [dennisreimann/ioctocat#288]
Any way to implement the milestones?

As first phase:

Group the issues at the issues-table by the linked Milestones, using Sections of the UITableView.

[MilestoneA]
ticketA
ticketB
[Tickets without Milestone]
ticketC
etc

Additional: 
Assign/edit milestones of a ticket

**Comment by iosdeveloper** [comment]
Maybe filter issues by arguments (like milestone) other than just open/close like on GitHub?

**Comment by dennisreimann** [comment]
v1.9 will be all about improved issue management. This will be added too :)

**Comment by jelledelaender** [comment]
Ok cool! I'm a new user to this application, finally an application for GitHub on the iPad. Although I build own software daily, I bought it in the App Store, I hope 1.9 will improve the issue-manager a lot, since this is a tool I use on daily base.

**Comment by dennisreimann** [comment]
If you are looking for a wonderful issue editor app for the iPad: Look no further than [BugHub](http://bughubapp.com/). It works great and is targeted specifically for managing issues on the iPad. I'm afraid iOctocat may never be as good as BugHub for this purpose, but that app is what my role model for that use case would be.

**Comment by jelledelaender** [comment]
I bought BugHub a time ago, but it's crashing every 2 minutes, makes it unusable to use.

Just did a re-install, I login, select only 2 repos and boom, crashed again. No go that project. I hope you don't `copy` the crashes, since iOctocat is doing quite fine.

**Comment by dennisreimann** [comment]
hehe, it works for me though, maybe I should stress test it more ;) 

there are some rough edges in v1.7.6 of iOctocat too, v1.7.7 is currently waiting for review and v1.7.8 is already cooking,…

**Comment by jelledelaender** [comment]
Ok, anyway, I'll contact BugHub since I cannot believe my account should be that different or weird. Curious to see iOctocat 1.9 :smile:

**Comment by potsky** [comment]
Hi! Thank you for this App and I am waiting too for next release with better issue management (personally just need milestone filter and applying milestone on an issue)

**Comment by potsky** [comment]
I just bought BugHub ! What a beautiful interface ! It works for me.
Eh eh new request : euuuh could you buy BugHub code source to integrate it in iOctocat ? Mouah ah !
