### ISSUE TITLE
Re-search if results autoreleased when browsing

### ISSUE THREAD

**Issue by JakeWharton** [dennisreimann/ioctocat#29]
If you search for something and browse deeply through the results your search term and results are autoreleased (or so i believe). I searched "iPhone" under repositories, went to "yammer_iphone", clicked to their website, and then clicked the link to view the full version of the site. Upon returning to the search results the list was cleared and the search box was empty.

I assume the embedded web view sucked up a lot of RAM so the list and term's memory were automatically released. The term should be stored securely and re-searched if the results were cleared.

**Comment by dennisreimann** [comment]
Hmm, I can't really verify this...

**Comment by JakeWharton** [comment]
Now I can't reproduce it either. It happened to me multiple times before and once today. Of course then I started up VNC and a video screen grabber for proof and couldn't get it to happen again. I'll try a few more times and see what I come up with.

**Comment by JakeWharton** [comment]
Can't reproduce. Must have been a local issue.

**Comment by JakeWharton** [comment]
Got it! Please re-open this issue (if commenting doesn't).

http://www.youtube.com/watch?v=KDZX5me9anU
