### ISSUE TITLE
Selecting the email cell on a profile results in a crash

### ISSUE THREAD

**Issue by iosdeveloper** [dennisreimann/ioctocat#290]

**Comment by dennisreimann** [comment]
seems to work for me (at least with the current master).

**Comment by iosdeveloper** [comment]
> Before using this class, you must always check to see if the current device is configured to send email at all using the `canSendMail` method. If the user’s device is not set up for the delivery of email, you can notify the user or simply disable the email dispatch features in your application. You should not attempt to use this interface if the `canSendMail` method returns `NO`.
