### ISSUE TITLE
Issue commenting: Save draft when going back

### ISSUE THREAD

**Issue by ruddfawcett** [dennisreimann/ioctocat#294]
I'll probably be able to implement this when I have a few minutes, but save the issue in user defaults for add comment uitextview?  I often find myself going back to the issue view to see who said what and make sure I am answering/responding to an issue well, and I have to copy my comment and then paste it after I return to add comment.  This would be a nice little feature.  Also, the user default would be destroyed when the issue view is gone.  This might be complicated to understand, so I'll implement this I think.

**Comment by dennisreimann** [comment]
I get it. Contribution welcome :)

**Comment by ruddfawcett** [comment]
I'm on this... just finishing up, then will submit a pull! :smile:

**Comment by ruddfawcett** [comment]
https://github.com/dennisreimann/ioctocat/pull/299
