### ISSUE TITLE
An empty email cell (n/a) presents an empty mail composer

### ISSUE THREAD

**Issue by maxbaeumle** [dennisreimann/ioctocat#297]
Only present a mail composer when an email address is available.

**Comment by iosdeveloper** [comment]
I can reproduce this on the profile of @maxbaeumle. Just search for him in iOc.

**Comment by iosdeveloper** [comment]
We might need to use `(!self.user.email.isEmpty)` instead of just `(self.user.email)`.

**Comment by iosdeveloper** [comment]
Turns out we need to use both. Preparing a fix...

**Comment by dennisreimann** [comment]
Yep, isEmpty only works in case a string is present.
