### ISSUE TITLE
User following

### ISSUE THREAD

**Issue by dennisreimann** [dennisreimann/ioctocat#3]
One should be able to follow/unfollow a user. The button for this should be placed on the user details view.

**Comment by intabulas** [comment]
following/unfollow is now implemented in the latest commits. We are finalizing the visual interaction and display before we close. 

Also note that the unfollow API is currently broken on the github side, it wont actually unfollow :) Nice part is it will all just magically work when scott fixes it on the github side

**Comment by dennisreimann** [comment]
Is there an issue about the broken unfollowing API yet? Too bad that the current API has so many flaws and inconsistencies, hope Scott has some time to fix them.

**Comment by intabulas** [comment]
I haven't gotten a chance to go look in the issues for the api.. The api call works, but it returns a new following list and the user you unfollow is still there and it shows up still in the following list in my profile on gh,

**Comment by intabulas** [comment]
there wasnt but there is now
http://github.com/develop/develop.github.com/issues/#issue/39

**Comment by dennisreimann** [comment]
I guess we can close this one.
