### ISSUE TITLE
Hide keyboard when clicking search not when results available

### ISSUE THREAD

**Issue by JakeWharton** [dennisreimann/ioctocat#30]
The keyboard should disappear when you click search rather than when the results become available. It prevents you from temporarily editing the term (to no affect) while results are loading and it is consistent with native app's search behavior.

**Comment by dennisreimann** [comment]
Hide keyboard when clicking search not when results available. Closed by f9997ec3e3e17911d5a9d63e28ddd7affc13c5e8
