### ISSUE TITLE
Open all URLs highlighted in issues/comments in internal web view instead of leaving the app for Safari

### ISSUE THREAD

**Issue by iosdeveloper** [dennisreimann/ioctocat#300]

**Comment by iosdeveloper** [comment]
300th issue. Yay!

BTW, I cannot post emojis from iOc. Maybe text needs to be escaped?

**Comment by ruddfawcett** [comment]
Ahhh you beat me to it hahaha....

**Comment by iosdeveloper** [comment]
Maybe add a 'Open in Safari' action to the web view?

**Comment by ruddfawcett** [comment]
That'd be nice.  Did you see my pull with comment draft saving?  @iosdeveloper

**Comment by iosdeveloper** [comment]
Yeah. Like the idea but didn't look into the changes yet...

**Comment by ruddfawcett** [comment]
Cool, thanks... :smile:
