### ISSUE TITLE
Passcode option for app

### ISSUE THREAD

**Issue by zeorze** [dennisreimann/ioctocat#302]
Would it be possible to add a passcode option to the app similar to what the Dropbox app has?

**Comment by ruddfawcett** [comment]
A better option would be to have a setting to not save GitHub password?

**Comment by iosdeveloper** [comment]
I suggest not to persist the OAuth token and instead ask for a password on every sign in.
Could be implemented as a switch in the add/edit account controller.

**Comment by zeorze** [comment]
That would also be a solution that would work for me. 

I have several private repositories in my account and therefore would like another layer of protection when viewing the app. Yes my devices already have pincodes but I see the code stored within these private repositories as valuable as what might be stored in Dropbox.

In fact with the Dropbox app you can set it to also remove any data associated with the app on the device after 10 failed passcode attempts.

Just being paranoid that's all.

**Comment by ruddfawcett** [comment]
@iosdeveloper better for settings.bundle?

**Comment by dennisreimann** [comment]
I'm closing this for now, feel free to reopen it, if someone would like to implement it or also thinks this is necessary.
