### ISSUE TITLE
Dates differ from GitHub

### ISSUE THREAD

**Issue by iosdeveloper** [dennisreimann/ioctocat#307]
I think GitHub uses the date the issue was created on, whereas iOctocat uses the date the issue was last updated on.

**Comment by iosdeveloper** [comment]
I suggest to either sort issues by the `updated` date or stick to the `created` date. Sorting by `created` but using `updated` is confusing...

**Comment by dennisreimann** [comment]
Agreed, lets do it like on GitHub.
