### ISSUE TITLE
Negative relative timestamp

### ISSUE THREAD

**Issue by JakeWharton** [dennisreimann/ioctocat#31]
I think this happens when the timestamp of the entry is equal to the current time. It also might be due to timezone issues.

Screens:
http://www.flickr.com/photos/jakewharton/3520521569/
http://www.flickr.com/photos/jakewharton/3520521775/

**Comment by dennisreimann** [comment]
Fixed negative relative timestamps. Closed by abbe3bb3309026caaa0da3de4b383053e0f1a9dd
