### ISSUE TITLE
Repository: List stargazers

### ISSUE THREAD

**Issue by elvisimprsntr** [dennisreimann/ioctocat#315]
Add the ability to see who has starred a particular repo.

**Comment by dennisreimann** [comment]
Yep. This would actually make for a good task for someone who'd like to contribute to the app. Almost everything for this feature is in place, it basically just needs to get wired up. Here's the [API for that](http://developer.github.com/v3/activity/starring/#list-stargazers)

**Comment by MazyM** [comment]
Hi, may I implement this feature?

**Comment by dennisreimann** [comment]
Yep, go ahead and ask in case you need help. Here's what I'd basically do: add a GHUsers property called stargazers to GHRepository. This should be instanciated lazily, see the other association properties as an example. 

After that you can add a cell to the Repository.xib, hook it up in The RepositoryController and push a UsersController with the repository.stargazers when the cell gets selected.

**Comment by MazyM** [comment]
Thanks for detailed plan, how to implement the feature. I will do pull request as soon as possible.
What do you think about adding **Starred repos** in the user's profile? If Starred repos is clicked, the user's starred repositories will show up.

**Comment by dennisreimann** [comment]
Closed by ed965eba01806c9a79e1681aa537fb912ab6155f. Thanks again @mazanma3

**Comment by dennisreimann** [comment]
> What do you think about adding Starred repos in the user's profile? If Starred repos is clicked, the user's starred repositories will show up.

Good idea, I just created an issue for that: #325 - go ahead if you like :)
