### ISSUE TITLE
WebView: Clear cache on sign out

### ISSUE THREAD

**Issue by iosdeveloper** [dennisreimann/ioctocat#317]
The web view cache is currently shared across accounts. I suggest clearing it on sign out (if that is even possible).

**Comment by dennisreimann** [comment]
That does not seem to be possible at the moment, because all one can do is deactivate the NSURLCache, and [we are doing that already](https://github.com/dennisreimann/ioctocat/blob/master/Classes/iOctocat.m#L256).

**Comment by iosdeveloper** [comment]
But we are only doing that on app launch, not when switching accounts...

**Comment by dennisreimann** [comment]
I'll check whether or not this will make a difference, because with our setting it shouldn't cache anyways in the first place.

**Comment by dennisreimann** [comment]
Sorry, that does not work :(
