### ISSUE TITLE
GitHub System Status: Display with statusbar color

### ISSUE THREAD

**Issue by dennisreimann** [dennisreimann/ioctocat#321]
The current way of checking the system status on every activation of the app is somehow obtrusive, because it gets in the way when switching back and forth between iOctocat and another app.

The status should still be checked on every activation, but instead of immediately showing the warning/error message just the statusbar should get colored in yellow/red. When tapping the statusbar when it is in warning/error-mode, the GitHub Status Message should be shown.

In case the GitHub Status is good, the bar should be kept as it is/cleared to normal state.

**Comment by ruddfawcett** [comment]
How about a less intrusive slidedown like instagram?

**Comment by ruddfawcett** [comment]
You might want to look at "OctoStatus" @dennisreimann
