### ISSUE TITLE
Account: Fix navigation UI glitches after signing out

### ISSUE THREAD

**Issue by iosdeveloper** [dennisreimann/ioctocat#331]

**Comment by dennisreimann** [comment]
BEWARE: This is a rabbit hole. I've been down there...

Could not find a way to fix this and after all the time I've spent on this I don't think it's worth to investigate any further. The only thing that's glitchy is that the title (new Account / Edit Account) does not get transformed into the navigation bar from the right, but pops up (without animation) once the view is in place. 

It certainly has something to do with [the slidingViewController reset](https://github.com/dennisreimann/ioctocat/blob/65330c6d0f1534833449f67e14626842edc032c3/Classes/MenuController.m#L104) happening when the account (menu and top view controller) gets dismissed. We reset the frame of the navigation controller, which should not be a problem actually. I suspect there's something going on under the hood I wasn't able to figue out.
