### ISSUE TITLE
Add "Load 25 more..." to bottom of search results

### ISSUE THREAD

**Issue by JakeWharton** [dennisreimann/ioctocat#34]
Self expanatory. I'm not sure if the API tells you totals but if there are no more results obviously don't show it and if there are less than 25 left then change it to reflect the proper number.

**Comment by dennisreimann** [comment]
Unfortunately the API doesn't support this yet...

**Comment by ddustin** [comment]
I second that request.  Any news / guesses as to when github plans on improving the API?  This seems like a pretty standard feature.

**Comment by dennisreimann** [comment]
I guess the new v3 of the API supports this. I'm currently very busy but will try to find the time for hacking on iOctocat around xmas...

**Comment by dennisreimann** [comment]
The API v3 now spits out enough results :)
