### ISSUE TITLE
Fix NSInternalInconsistencyException in - [AFHTTPClient initWithBaseURL:]

### ISSUE THREAD

**Issue by dennisreimann** [dennisreimann/ioctocat#345]
## Stacktrace

<pre>AFHTTPClient;initWithBaseURL:;;
GHOAuthClient;initWithBaseURL:;GHOAuthClient.m;7
GHAccount;apiClient;GHAccount.m;74
GHResource;apiClient;GHResource.m;37
GHResource;loadWithParams:path:method:start:success:failure:;GHResource.m;55
GHResource;loadWithParams:start:success:failure:;GHResource.m;49
IOCAuthenticationController;authenticateAccount:;IOCAuthenticationController.m;29
IOCAccountsController;openOrAuthenticateAccountAtIndex:;IOCAccountsController.m;118
-;start;;</pre>

## Reason

**\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: url'
## Link to HockeyApp
- [https://rink.hockeyapp.net/manage/apps/19374/app_versions/21/crash_reasons/2918876](https://rink.hockeyapp.net/manage/apps/19374/app_versions/21/crash_reasons/2918876)

**Comment by ghost** [comment]
Test

**Comment by ghost** [comment]
One more

**Comment by ghost** [comment]
Think I nailed it now ;)
