### ISSUE TITLE
Only a subset of starred Repositories are loaded into the Starred-List

### ISSUE THREAD

**Issue by senfomat** [dennisreimann/ioctocat#348]
I've noticed, that in the list of my star-ed github-repos only 30 are loaded, without any possibility to load further. As I have 53 starred, I miss some of them.

**Comment by iosdeveloper** [comment]
Duplicate of #177. Closing...

**Comment by dennisreimann** [comment]
@senfomat we will address that soon, it will be done in v1.9 as other parts of the app also lack pagination.
