### ISSUE TITLE
No user pictures in feeds

### ISSUE THREAD

**Issue by thilo** [dennisreimann/ioctocat#35]
iphone G2 Version 2.2 ioctocat 0.9

**Comment by dennisreimann** [comment]
The gravatars get loaded when you open the detail view for an user, because we don't have the email address in the feed view. The users email address must be public und he needs to have an gravatar - can you check this?

Once loaded the gravatar gets cached and displayed within the other views...

**Comment by JakeWharton** [comment]
You could have a background queue that does `/user/show/username` and then loads the gravatar from their email address. It might be useful to only add users to this queue if an entry from them is currently visible on screen.

**Comment by thilo** [comment]
or you ask the git hub guys to include the gravatar hash in the feed. That would solve the problem without exposing the email addresses.

**Comment by dennisreimann** [comment]
I sent Scott an email about that, maybe they can include the hash value in the feed - that would be the best soluton in my opinion.

**Comment by dennisreimann** [comment]
Load gravatars on demand. Closed by e83733162bcec9da1c5ae78030fbd5ee34a85b7d
