### ISSUE TITLE
Can't authorize correctly for the first time app runs

### ISSUE THREAD

**Issue by zhen9ao** [dennisreimann/ioctocat#350]
Start up the app for the first time, add a new account. After `save`, it says `auth ok`, but not navigate back automatically. If I push back button manually, and then click on the account just added, the `auth fail` will appear.

**Comment by dennisreimann** [comment]
Have you tested it with the current master? I'm asking because I fixed that in d91e69fde9ac1a0f7ae48027398bee8c0c635d63

**Comment by zhen9ao** [comment]
Yeah, I test it with the current master branch code

**Comment by dennisreimann** [comment]
Hmm, that works for me, can you debug this somehow? The last time this failed was because the account.apiClient was not set correctly. 

@iosdeveloper cann you reproduce it with the current master?

I just pushed some more account changes, but non of those should be related to this problem.

**Comment by iosdeveloper** [comment]
Can reproduce the problem if I revoke the app on GitHub and authorize again. I cannot login anymore after that. Same reason?

**Comment by dennisreimann** [comment]
k, I think I fixed it, dare to reopen it, if it still occurs.
