### ISSUE TITLE
pull to refresh stuck in action

### ISSUE THREAD

**Issue by Showtimes** [dennisreimann/ioctocat#353]
Latest release pull to refresh remains stuck midway down after pull to refresh action and does not retract all the way back up. 

It seems to be sporadic in occurrence.

**Comment by Showtimes** [comment]
Using iPhone 5 forgot to mention.

**Comment by iosdeveloper** [comment]
Seems to occur if the response to a request is received in a too short amount of time.

**Comment by iosdeveloper** [comment]
`SVPullToRefresh` is used as dependancy for that, so you might want to report the issue there too. I already suggested to use `UIRefreshControl` in iOS 6 though...
