### ISSUE TITLE
Limit on comments displayed?

### ISSUE THREAD

**Issue by kstrauser** [dennisreimann/ioctocat#358]
In trying to view [a commit with lots of comments](https://github.com/python/pycon-code-of-conduct/commit/500a3d25c27065598002f7c999de3fdfb7ab18b1), iOctocat doesn't seem to show any after the first 100. Is that by design or by accident?

**Comment by dennisreimann** [comment]
Sorry for that, iOctocat currently does not support pagination. We will address this with #177.

I'll leave this open so that you'll be noticed, once this will be fixed!

**Comment by kstrauser** [comment]
Right on. Thanks!
