### ISSUE TITLE
Trouble on Build - Character Error on Unit Tests

### ISSUE THREAD

**Issue by ussjoin** [dennisreimann/ioctocat#36]
I'm using iPhone SDK 3.0b5. When building (either for OS 2.2.1 or 3.0b5), I get the following error:

> <com.apple.tools.product-pkg-utility>: error: CFBundleIdentifier 'de.dennisbloete.Unit_Tests' contains illegal character '_' 

I've tried several different things, but nothing seems to get rid of the error. Is there some flag I can use to make it stop trying to build the unit tests, or how can I make this go away? (I haven't modified the source files at all, so AFAICT, anyone trying to do a fresh clone followed by a build will encounter this problem.)

**Comment by dennisreimann** [comment]
Do the latest commits fix that for you? The message about the invalid character disappeared, but at least I seem to have another problem - XCode 3.1.3 can't find the SenTestingKit framework...

If it still doesn't work and you want to build a new version for yourself you can remove the UnitTests as a direct dependency -> double click the iOctocat target and in the General tab remove the direct dependency.

**Comment by ussjoin** [comment]
The latest commits do fix this for me, and I do not have the SenTestingKit issue you mentioned. I did not have to remove the unit tests as a dependency.

**Comment by dennisreimann** [comment]
okay.
