### ISSUE TITLE
MenuController not act the same in iOS5 as it is in iOS6

### ISSUE THREAD

**Issue by zhen9ao** [dennisreimann/ioctocat#362]
Login with an account, in the menu, press `back button`, and there it is:

![iOS Simulator Screen shot Mar 25 2013 9 58 37 PM](https://f.cloud.github.com/assets/703196/298597/6c3b080c-9561-11e2-8db2-cba63b4dc970.png)

topViewController won't go away. And iOS6 don't have this issue.

**Comment by dennisreimann** [comment]
This is on the current master and it works in the latest App Store version, right?

**Comment by zhen9ao** [comment]
I'm not sure with that, cus I don't have iOS5 device on hand.

**Comment by zhen9ao** [comment]
It's OK before commit e76c9d1ac8bdded509d7033be915a1a5eaaae8a5

**Comment by dennisreimann** [comment]
That's what I thought, thanks.

**Comment by dennisreimann** [comment]
I think we will raise the deployment target for v1.8 to >= iOS 6
