### ISSUE TITLE
App crashes when user tries to dismiss MFMailComposeViewController

### ISSUE THREAD

**Issue by ghost** [dennisreimann/ioctocat#368]
If I bring up the mail composer by tapping on the email address of a user and then try to dismiss it, without saving a draft, the app crashes with EXC_BAD_ACCESS code=1.
Error produced on iOS 6.1.3 iPhone + Simulator
I have already tried to fix it but I honestly have no idea how :/

![Screen Shot 2013-03-27 at 18 17 17](https://f.cloud.github.com/assets/3141423/309514/3ee19982-9702-11e2-99cc-11e83e7ea09d.png)

**Comment by iosdeveloper** [comment]
Can you reproduce the issue with the App Store version? In that case, please submit a crash report.

**Comment by ghost** [comment]
It works with the App Store version o.O

**Comment by iosdeveloper** [comment]
I suspect it has something to do with c0e9d08 ... @dennisreimann
