### ISSUE TITLE
Commenting on lines of code in pull request

### ISSUE THREAD

**Issue by iainbeeston** [dennisreimann/ioctocat#374]
So far as I can tell it's not possible to comment on a particular line of code in a pull request, only on the pull request as a whole. Also, I can't see comments left by other people (except by looking in the feed for that repository)

**Comment by dennisreimann** [comment]
>  it's not possible to comment on a particular line of code in a pull request

Good point.

>  Also, I can't see comments left by other people (except by looking in the feed for that repository)

The pull request comments are shown on the pull request view (at the bottom), but I think I didn't get the question right...

**Comment by iainbeeston** [comment]
The comments that are missing from pull requests in ioctocat are comments
on specific lines of code made by other people (normally, on the github
website, when I go to the files tab for a pull request there are comments
mixed in with the source files) - but I can see in ioctocat comments
made on the pull request as a whole.

## 

Iain

**Comment by dennisreimann** [comment]
Ah, thanks for clarifying that.
