### ISSUE TITLE
Markdown files not shown correctly in code browsing

### ISSUE THREAD

**Issue by dvdmelamed** [dennisreimann/ioctocat#375]
Although the main repo README.md file is correctly identified as Markdown file and shown from in the repo main view, the file is shown as a text file when browsing the repo code

**Comment by dennisreimann** [comment]
yep, the code browser displays the raw version, but that's intended, because we don't show a rendered version of html either... I'll leave this open as a feature request for toggling between raw and rendered version of a markdown file, okay?

**Comment by dvdmelamed** [comment]
Sure. Apart for that, awesome app. Should be in the Essentials of each dev!

**Comment by dennisreimann** [comment]
Thanks! There are still some more things that would improve it, but v1.8 with push notifications for GitHub notifications is almost finished and v1.9 will be all about the issue/pull requests tickets here in the tracker... 

btw: I would totally appreciate it, if you'd take the time to write a review on the App Store or recommend the app to your colleagues ;)

**Comment by dvdmelamed** [comment]
Exciting news. Just submitted my review to the App Store. Keep up with the great work

**Comment by dennisreimann** [comment]
Thanks a lot! I'm also working on a new website that also features a roadmap for the upcoming things and has the CHANGELOG so that it is more transparent what we are working on and plan to do :)
