### ISSUE TITLE
"created tag" entries in news feed pick wrong repository name

### ISSUE THREAD

**Issue by intabulas** [dennisreimann/ioctocat#38]
when someone creates a tag on a repo and it shows up in the news feed, iOctocat is picking up the tag value as the repository name and not the repository name itself

As an example if the feed contains "aslakhellesoy created tag v0.3.7.5 at aslakhellesoy/cucumber" then "v0.3.7.5" gets picked up as the repo name and not "cucumber". 

The cause is the code used to identify a repo being created (both prefix event with 'create') isnt handling a 'tag' being created

**Comment by dennisreimann** [comment]
That should be easy to fix :)

**Comment by dennisreimann** [comment]
Fix for create tag events in feed entry. Closed by 353c007d1f6b63ac37799727a84dcbca12185e19
