### ISSUE TITLE
Error when running in Xcode

### ISSUE THREAD

**Issue by kenetik** [dennisreimann/ioctocat#382]
CpResource Assets/highlight.js/src/styles/arta.css /Users/_user_/Library/Developer/Xcode/DerivedData/iOctocat-bxhwxcrrqtzbkpduhrztkshjoeyu/Build/Products/Debug-iphonesimulator/iOctocat.app/arta.css
    cd "/Volumes/Spinning Storage/Development/GitHub/ioctocat-master"
    setenv PATH "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks "/Volumes/Spinning Storage/Development/GitHub/ioctocat-master/Assets/highlight.js/src/styles/arta.css" /Users/_user_/Library/Developer/Xcode/DerivedData/iOctocat-bxhwxcrrqtzbkpduhrztkshjoeyu/Build/Products/Debug-iphonesimulator/iOctocat.app

error: /Volumes/Spinning Storage/Development/GitHub/ioctocat-master/Assets/highlight.js/src/styles/arta.css: No such file or directory

What am I doing wrong?

**Comment by dennisreimann** [comment]
Hey @kenetik, did you follow the steps described in the [development docs](/dennisreimann/ioctocat/blob/master/DEVELOPMENT.md#building-the-project)?
