### ISSUE TITLE
Edit and Push

### ISSUE THREAD

**Issue by JSFun** [dennisreimann/ioctocat#390]
Editing Files right on iOS devices, so you can do that on-the-go Would be Great.

**Comment by dennisreimann** [comment]
We discussed this a few times and my honest amswer to that is that I don't really see this coming. This is a really big task as I would also have to ship an editor that works really good on the iPhone. 

I personally would not want to edit code on the iPhone, except for maybe fixing README typos. 

For now, I see the purpose of iOctocat in staying up to date and having a quick and good way to respond to issues, pull requests and so on. v1.9 is all about improving the issues management and 2.0 will be about bringing the rest of the app in shape (like proper iPad interfaces). 

Sorry, but that's what I'm thinking about it currently - so don't expect this feature to land anytime soon.

**Comment by JSFun** [comment]
So what about just using a modalViewController with a Standard Textbox on it or let people edit it right in the WebView which I assume you are using for Displaying code? I don't want to edit files on iPhone either, but I'd love to do that on my iPad as the 9.7" are really great for Textediting.

**Comment by dennisreimann** [comment]
> So what about just using a modalViewController with a Standard Textbox on it or let people edit it right in the WebView 

That just does not cut it. Next thing I bet will be people complaining about the crappy experience when editing code and at that point I just cannot remove the feature but would have to spend tons of time implementing a proper editor. Don't get me wrong, I'm not fully against that feature, but in case I'll add it, it has to work really good.

**Comment by iosdeveloper** [comment]
BTW, the "Open in..." feature was implemented exactly for that, so you can open and edit in other apps like Textastic, though there is no way to get the changes back to GitHub in iOctocat...
