### ISSUE TITLE
Repository watching

### ISSUE THREAD

**Issue by dennisreimann** [dennisreimann/ioctocat#4]
One should be able to watch/unwatch a repository. The button for this should be placed on the repository details view.

**Comment by JakeWharton** [comment]
It would be nice to be able to watch/unwatch a user too.

edit: Oops!

**Comment by dennisreimann** [comment]
Hey Jake, there is already an issue about that: #3

**Comment by dennisreimann** [comment]
I think we should implement the actions like we did with the user following and keep the watchlist for a later version.

**Comment by intabulas** [comment]
repo watching is done and commited, though until we can get a watch list we cant effectively do "unwatch"

**Comment by dennisreimann** [comment]
Implemented faked watchlist. Closed by e64b2a104b1734e01df7726f57e3d512d3014bf5
