### ISSUE TITLE
Profile > Following shows followers

### ISSUE THREAD

**Issue by priteau** [dennisreimann/ioctocat#40]
When I do Profile > Following in iOctocat 1.0 I see my followers (actually, my only follower).
Or maybe it's the intersection of followers and following. Anyway there is a bug.

**Comment by roidrage** [comment]
I can confirm this bug. iOctocat also crashes on me a couple of seconds later, after I tried to look at both Following and Followers.

**Comment by priteau** [comment]
The fix for this issue is in my repo, and I just sent a pull request to Dennis.

By the way, iOctocat never crashed on me.

**Comment by dennisreimann** [comment]
Applied... can't confirm the crashes though...
