### ISSUE TITLE
Authentication issues when accessing app from a push notification

### ISSUE THREAD

**Issue by OliverJAsh** [dennisreimann/ioctocat#405]
When I open the app from a push notification, I get a spinning wheel with "Authenticating…" – this continues and doesn't stop. If I access the app normally, there are no authentication issues.

**Comment by dennisreimann** [comment]
Can you try to reauthenticate the account? To do so, please go to the account editing view (blue button on the right of the accounts list), enter your credentials and save.

I'll check what's wrong on our side, thanks for reporting the issue :)

**Comment by OliverJAsh** [comment]
I just got a notification when you replied, haha. I got a few of the details wrong. I get a red banner along the top that says "Missing account" (showing my news feed in the background) and then I can continue to use the app. So actioning a notification doesn't actually take me to the item.

I have tried re-authenticating!

**Comment by dennisreimann** [comment]
I'll investigate tomorrow, thanks for providing more details :)

**Comment by dennisreimann** [comment]
Can reproduce it: This happens when the app has to do a full launch and does not launch from memory. Will fix it in v2.0!

**Comment by dennisreimann** [comment]
Fixed :)
