### ISSUE TITLE
Display pull request status

### ISSUE THREAD

**Issue by retronym** [dennisreimann/ioctocat#406]
See: https://github.com/blog/1227-commit-status-api

**Comment by dennisreimann** [comment]
Already works like that.

![foto 1](https://f.cloud.github.com/assets/886/873668/c0d20144-f87c-11e2-950a-aad1f0b875bc.PNG)
![foto 2](https://f.cloud.github.com/assets/886/873666/bd340d3e-f87c-11e2-8fc2-b0b52507d0f6.PNG)
