### ISSUE TITLE
Bug in 2.0: Markdown Parser too greedy

### ISSUE THREAD

**Issue by klaustopher** [dennisreimann/ioctocat#407]
While discussing on an issue I saw that: 

![too greedy](https://www.dropbox.com/s/gwof4ts1qkrruzw/Foto%2004.08.13%2023%2018%2019.png)

When there are multiple `inline code elements` in an issue, the parser is `too greedy` and highlights too much as code.

**Comment by dennisreimann** [comment]
Thanks!

**Comment by dennisreimann** [comment]
Will be fixed with v2.0.1 :)

**Comment by dennisreimann** [comment]
Reference tisba/gst-kitchen#17
