### ISSUE TITLE
234

### ISSUE THREAD

**Issue by heyuan110** [dennisreimann/ioctocat#408]
23412341324123412341234去w而324132p4ui231破4123普o1p23p123ui4ip123io4p123iu4214up32哦4up123u4p1哦2u34p312u4p1欧34p1哦2u34破123u4破12u34p12u34破12ui34破12u4p1io23u4哦p123412341234

**Comment by dennisreimann** [comment]
Fixed in the upcoming v2.0.1 

Can you update your App Store review once the new versin with the fix available?

**Comment by dennisreimann** [comment]
The fixed version is available on the App Store now. 

@heyuan110 can you verify it works now and then update your review please?
