### ISSUE TITLE
"Could not load the repositories" when visiting a committer page

### ISSUE THREAD

**Issue by priteau** [dennisreimann/ioctocat#41]
When going from a commit to a the committer, I often get the following error:
"Could not load the repositories"

This is because iOctocat couldn't find the committer page, since the name in the committer doesn't match the username on GitHub.
However, GitHub has no problem matching these commits with the right account (from the github.user configuration entry, or from the email address?).

Maybe you should ask the GitHub devs to export the github username in the commits API to solve this issue.

**Comment by dennisreimann** [comment]
yeah, I think it would be best if GitHub could clean this up... this just isn't consistent, because sometimes they use the real name and other times the username appears...

**Comment by dennisreimann** [comment]
I filled a ticket for the GitHub API: http://support.github.com/discussions/api/68-commits-atom-feed-inconsistent-name-tag

**Comment by dennisreimann** [comment]
Okay, parsing the URI attribute like proposed here could be a solution for that: http://support.github.com/discussions/api/68-commits-atom-feed-inconsistent-name-tag

**Comment by dennisreimann** [comment]
Retrieving correct user login in feed entry. Closed by 6afcfa33c7d588c737c5e909e55faefb47237eea
