### ISSUE TITLE
Proper iPad support

### ISSUE THREAD

**Issue by matthewelse** [dennisreimann/ioctocat#415]
Hi, given that there are no good Github apps for iPad, would you consider making the app a universal app that works for both iPad and iPhone? I'm sure much of the code could be reused, but I'm sure many people would agree that this would be useful.
Sorry if I posted this in the wrong place :)

**Comment by matthewelse** [comment]
Never mind, this seems to be in the code already sorry. But it doesn't seem to be in the app store screenshots... does that mean it isn't there or just that there aren't any screenshots?

**Comment by dennisreimann** [comment]
Hello, thanks for your feedback!

Please keep in mind, that this is the codebase for v1 of iOctocat. I recently wrote something up [about the iPad version of iOctocat v2](http://dennisreimann.de/blog/ioctocat-github-for-ios/), I guess that explains it best.

**Comment by matthewelse** [comment]
Does the current app on the app store have a nice interface for iPad, or is it just scaled up iPhone (there are only screenshots for iPhone)

**Comment by dennisreimann** [comment]
As written in the blog post, v2 isn't universal anymore. There will be a separate iPad app in the future.

**Comment by matthewelse** [comment]
oh right I get it, seems obvious now, thanks :smile:

**Comment by matthewelse** [comment]
btw thanks for the app, it's pretty much the only nice Github App out there

**Comment by dennisreimann** [comment]
Thank you!
