### ISSUE TITLE
Any plan for offline code view?

### ISSUE THREAD

**Issue by taiwen** [dennisreimann/ioctocat#416]
Just purchased the app, looks great. Wondering do you have plan to support offline code view?

**Comment by dennisreimann** [comment]
Sometimes people ask for that, but right now I'm just checking the demand for that feature.

As the next thing would be, that people would like to edit code and push that back to GitHub, this might be a really big feature and there are more relevant things (like iOS 7 adaption and iPad UI) on the roadmap right now.

Did you have a look at the GitMongo app? That might be what you are looking for and what you could use until iOctocat might integrate something like that.

**Comment by dignifiedquire** [comment]
I think it would be great have the ability to subscribe to a repo so it keeps an offline version around and updates when network is available. If I'm on the road often the signal drops for a half an hour or so and this would allow for continued reading in between.
I don't think editing is something I want to do on my iPhone and on the iPad a dedicated editor makes much more sense then to integrate that here.

**Comment by taiwen** [comment]
These days I have been out of town but keep reading our github repos. It is really a painful experience with poor Internet connection. Look forward to seeing the feature implemented, in the mean time, I will check other app.
