### ISSUE TITLE
Can't authenticate into app with 2 factor authentication turned on.

### ISSUE THREAD

**Issue by tarebyte** [dennisreimann/ioctocat#419]
Hi there I don't know if this is an issue that has already been brought up before, I didn't see it.

If you need any logs from XCode let me know.

**Comment by dennisreimann** [comment]
Which version are you using? You will need the current v2.1 from the App Store for this to work. 

As you mention Xcode logs I think you are using the code from this repository: Keep in mind that the open sourced code base is for v1, which does not support 2FA and is kinda outdated by now, as I stopped pushing here two months ago.

**Comment by tarebyte** [comment]
Gotcha, so will this repo always stay on v1?

**Comment by dennisreimann** [comment]
yes, so don't expect any updates. 

I'm just keeping it open source because v1 always was open and people really seemed to like it that way.
