### ISSUE TITLE
Cannot find protocol declaration for 'BITFeedbackManagerDelegate' on iOS 7

### ISSUE THREAD

**Issue by abhinavn** [dennisreimann/ioctocat#420]
Hi

I cloned the project and I tried building it with Xcode 5 and iOS 7 I am getting the following error

/Users/nallagun/Git/ioctocat/Pods/Headers/HockeySDK/BITFeedbackManager.h:120:32: Cannot find protocol declaration for 'BITFeedbackManagerDelegate'; did you mean 'BITHockeyManagerDelegate'?

My PodFile

platform :ios, '7.0'

gem 'cocoapods', '0.25.0'

pod 'AFNetworking', '1.2'
pod 'AFOAuth2Client', '0.1'
pod 'Base64'
pod 'SVPullToRefresh', '0.4.1'
pod 'SVProgressHUD', '0.9.0'
pod 'TTTAttributedLabel'
pod 'HockeySDK'
pod 'TPKeyboardAvoiding'
pod 'NSStringEmojize', :git => 'https://github.com/iOctocat/NSStringEmojize.git'
pod 'YRDropdownView', :git => 'https://github.com/iOctocat/YRDropdownView.git'
pod 'ECSlidingViewController', :git => 'https://github.com/iOctocat/ECSlidingViewController.git'
pod 'Expecta', '~> 0.2.1'
pod 'KIF', '~> 2.0.0'

post_install do |installer|
  require 'fileutils'
  FileUtils.copy 'Pods/Pods-Acknowledgements.plist', 'Settings.bundle/CocoaPodsLicenses.plist'
end

All i did was add additional KIF pod. What is causing this issue?

Thanks

**Comment by abhinavn** [comment]
The header file referred in ../Git/ioctocat/Classes/IOCMenuController.m:26:9 is throwing error, if it helps

I am running on simulator

**Comment by dennisreimann** [comment]
That's a problem in the current HockeySDK-iOS, see bitstadium/HockeySDK-iOS#63

However: Keep in mind that this is the source for v1 of iOctocat which isn't maintained anymore - this is not the version you are seeing on the App Store.
