### ISSUE TITLE
No merge button for pull request

### ISSUE THREAD

**Issue by bettse** [dennisreimann/ioctocat#421]
When I visit a PR that I created, on a repo that I'm a contributor for, that I could merge through the web ui, I don't see any merge button on iOctocat.  It doesn't look like http://pic.twitter.com/JPyQY8941x as I would expect.  Based on that tweet, I checked and the repo I'm working with returns "Issues are disabled for this repo" for /repos/:owner/:repo/assignees .  Using Debug/api.rb I got that message with a status of "410 Gone".

Is this a bug?

**Comment by dennisreimann** [comment]
Which version are you using? You can find the version and build number at the bottom of the left hand menu.

**Comment by bettse** [comment]
2.1.2 build 211
-- 
Eric Betts
http://ericbetts.org

On October 15, 2013 at 10:02:32 PM, Dennis Reimann (notifications@github.com) wrote:

Which version are you using? You can fin the version and build number at the bottom of the left hand menu.

**Comment by dennisreimann** [comment]
Alright, I'll talk to GitHub about this. IMHO the assignee lookup should work, even the repos issues are disabled. 

The reason that this fails is that the call to find out whether or not you are assigned does not work. 

Thanks for debugging this in advance, that really saves a lot of time and headache!

**Comment by dennisreimann** [comment]
Hey Eric, can you try again now? GitHub said they fixed it :)

**Comment by bettse** [comment]
That was fast!  Yup the button is there now.  Thank you.

**Comment by dennisreimann** [comment]
Awesome, thanks for the feedback!

**Comment by bettse** [comment]
I'm not sure if it's you, me, or the GitHub API, but I'm not seeing the button again.  I do see the messages indicating tddium passed for my PRs.

**Comment by dennisreimann** [comment]
I got that report from another user as well and found a bug that I introduced recently that might cause this to happen. 

We are currently in the beta period for v2.2.0 and checking if it's fixed, thanks for reporting that :)
