### ISSUE TITLE
Gist notifications

### ISSUE THREAD

**Issue by balupton** [dennisreimann/ioctocat#423]
Is it possible for iOctocat to also notify me of comments on gists. It is a highly requested feature that github doesn't yet support itself, despite providing an api for it.

More information / backstory here: https://github.com/isaacs/github/issues/21

**Comment by dennisreimann** [comment]
Yep, as you said there is no API for that and GitHub does not even trigger gist events anymore, so that they don't get shown in the news feeds. That changed some time ago, I don't know why.

**Comment by balupton** [comment]
There is an api for this: http://developer.github.com/v3/gists/comments/#list-comments-on-a-gist

**Comment by dennisreimann** [comment]
There is an API for commenting on gists, but no events/activities for those comments. See http://developer.github.com/v3/activity/events/types/
