### ISSUE TITLE
combine gists

### ISSUE THREAD

**Issue by cfoellmann** [dennisreimann/ioctocat#425]
how about reducing menu items and combining "Gists" and "Starred Gists" by using the "switch" up top.
This way the menu is reduced by one item and one section.

**Comment by dennisreimann** [comment]
I'd rather kill that section in the menu then - but where to put the Gists menu item then? I also think it makes sense to have them separated: imho they are different kinds of things I'd like to access. 

Let's track this as an enhancement request and see what others think :)
