### ISSUE TITLE
Q: GitLab support?

### ISSUE THREAD

**Issue by cfoellmann** [dennisreimann/ioctocat#426]
I know it is really far off the scope of the app but would it be possible to add support for GitLab accounts? GitLab.com cloud and self-hosted.

Would be worth an in-app purchase. Although I hate these I would really love it.

**Comment by dennisreimann** [comment]
Nope, I talked to them, unfortunately their APi is incompatible so this would be more of a separate app.

**Comment by joewiz** [comment]
Bummer.

**Comment by joewiz** [comment]
Ah, further searching yielded [this suggestion](https://twitter.com/gitlab/status/452750763480334337) from the GitLab folks: http://gitlabcontrol.com/. Would be nice to have GitLab support in iOctoCat, but it looks GitLabControl will suffice.
