### ISSUE TITLE
search by org/repo

### ISSUE THREAD

**Issue by queckezz** [dennisreimann/ioctocat#431]
Sometimes repositories have really generic names like `dom` or `menu` and are not really that popular. So it becomes really hard to just search for these generic names and find the right one in this giant list that comes up. It would be awesome if we could not only search by the repo name OR the organization name but both. On github desktop you can just search for `component/dom`, `stagas/menu`.

Thanks for the awesome app btw!

**Comment by dennisreimann** [comment]
Thanks for your feedback :)

Right now the problem seems to be that the slash doesn't get encoded properly - I'll take a look and fix this with the upcoming update if it's that simple :)
