### ISSUE TITLE
Are there notifications for news feed items?

### ISSUE THREAD

**Issue by Casuallynoted** [dennisreimann/ioctocat#432]
Hello! I just recently started using iOctoCat, and I really love being able to get activity notifications on the go. I was wondering, are news feed items, like commits, also a part of push notifications? I haven't gotten any new news feed items since I started using it, so I don't know. XD

Thanks!
Casuallynoted

**Comment by dennisreimann** [comment]
Hey, thanks for your feedback :)

Right now the push notifications are for GitHub notifications only, some more details about that are here: http://ioctocat.com/faq

You aren't the only one asking for that feature, though. I myself would consider this too noisy as the news stream also contains starring etc., but I'm noting this as a :+1: on the feature request ;)

**Comment by Casuallynoted** [comment]
You might be able to do sliders that decide what type of notifications the app can give you! That way, users can customize their push notifications. Thank you so much for responding so fast! This is a really awesome app! :D
