### ISSUE TITLE
Cant login after purchasr

### ISSUE THREAD

**Issue by rogeralsing** [dennisreimann/ioctocat#434]
After purchasing the app, it is no longer possible to log in. "Authentication faiblesse"

**Comment by dennisreimann** [comment]
Hey Roger, first of all: Sorry for that!

I had the same thing reported yesterday and am investigating what's leading to this. Right now the only solution seems to be to remove the app, redownload it and log in again.

As this does not seem to happen for everyone who upgrades, it would be nice if you could give me some details: Do you have 2FA enabled? If so, does it happen before or after you provide the 2FA code?

I guess you upgraded, got prompted to login and then this happened, right?

**Comment by bomberstudios** [comment]
Hi there. I just experimented this same problem, and I uninstalled and reinstalled the app. 

Still doesn't work : /

**Comment by rogeralsing** [comment]
Same for me. Tried multiple times to delete and install.

**Comment by dennisreimann** [comment]
Okay, so both of you uninstalled and reinstalled the app?
Can you please provide the answers for the other questions? That'd help to debug, thanks!

**Comment by bomberstudios** [comment]
- I don't have 2FA
- I have deleted and reinstalled just once
- I upgraded to basic, was told to logout, and now I cannot login again (I've triple checked my password)

Could this be related to non-alphanumeric symbols in the password?

**Comment by dennisreimann** [comment]
No, I'm also using non-alphanumeric characters and your initial login with the free version did work with the same password, right?

**Comment by bomberstudios** [comment]
It was a shot in the dark : )

**Comment by dennisreimann** [comment]
No problem, I'm thankful for every hint, because I haven't succeeded in reproducing this yet. Besides the two of you there is another user that reported this, but it does not happen for everyone - for the majority it works, which makes this even harder to understand. 

Thanks again for providing the additional information.

**Comment by bomberstudios** [comment]
It looks like I fixed it by deleting the authorization token for iOctocat on https://github.com/settings/applications

**Comment by bomberstudios** [comment]
(I actually had two of them, which may explain the login problem in the first place)

**Comment by rogeralsing** [comment]
Yepp, that solves it for me too

**Comment by bomberstudios** [comment]
Woohoo! :dancers:

**Comment by dennisreimann** [comment]
@rogeralsing did you also have two authentication tokens on GitHub.com?

**Comment by rogeralsing** [comment]
Yepp

**Comment by dennisreimann** [comment]
Alright, that'd also explain why the error occurs across reinstalls. Now i'll hAve to dig into why this happens in the first place. Thanks everyone.

**Comment by dennisreimann** [comment]
Can you tell me, how many authorizations are listed for you on this page? https://github.com/settings/applications

I'm suspecting the problem might occur when there are many authorizatons, as iOctocat does not paginate that list currently...

**Comment by rogeralsing** [comment]
Now there is only one listed.

**Comment by dennisreimann** [comment]
Okay, only iOctocat and not any other authorization (even for other apps)?

**Comment by rogeralsing** [comment]
yes, there was two IOctocat tokens before, now only one

**Comment by bomberstudios** [comment]
I had two iOctocat tokens listed. I removed both. This is what I have currently:

![screenshot 2014-02-22 21 11 50](https://f.cloud.github.com/assets/3832/2238715/cd237a20-9bfd-11e3-8980-c5baaf401f1c.png)

I also have 21 "Authorized applications" on the list below that one.

**Comment by dennisreimann** [comment]
Alright, thanks for your fast answers!

**Comment by dennisreimann** [comment]
Alright, found the error and fixed it :)

I just wanted to let you know that in about a week v2.3.3 will ship, which fixes this error - thanks for helping me debug this!

Cheers, 
Dennis
