### ISSUE TITLE
Enable iPad interface

### ISSUE THREAD

**Issue by cyberpower678** [dennisreimann/ioctocat#435]
Lovely app, with a few bugs. my primary concern is if you could create an interface for the iPad.  It's a shame to have to use the iPhone interface on an iPad and waste so much space and potential.  I would really love it.

**Comment by dennisreimann** [comment]
Thanks for your feedback :) i'm currently working on the iPad interface. 

Could you name the "few bugs"? That'd help to fix them ;)

**Comment by rogierslag** [comment]
Big fat like on an ipad interface! Especially since our sales force also learned github it would be great if they could work from their ipads too :)

**Comment by Lukasa** [comment]
@dennisreimann Is there any way I can financially support you for this (e.g. bug bounties)? I'd love my iPad to be my full-blown travel computing mode, but GitHub's web interface is pretty rough on iPad and iOctocat's is awesome.

**Comment by dennisreimann** [comment]
@Lukasa thanks for offering that :) right now there is no such thing, but I was aready thinking about something like a supporters in-app purchase. however, right now I just lack the time to work on the app, because I've got too much other work to do.

**Comment by Lukasa** [comment]
@dennisreimann I totally get that: finding time for open source is always hard. If you ever need anything to help free up your time let me know. =)
