### ISSUE TITLE
Push notification fails

### ISSUE THREAD

**Issue by cyberpower678** [dennisreimann/ioctocat#436]
Attempting to activate push notifications leads to a failure.  It also seems to be related to the authorization failure.

**Comment by dennisreimann** [comment]
With authorization failure you mean the behaviour described in #434? If so, do you also have multiple iOctocat OAuth tokens on the applications page on GitHub?

**Comment by cyberpower678** [comment]
I have 2 tokens.  One authorizes it to do stuff, and the other authorizes push notifications.  They both seem to work for the iPad and iPhone.  It also fixed itself when I re-installed the app on my iPad.

**Comment by cyberpower678** [comment]
I have both working now, with the 2 tokens.
