### ISSUE TITLE
No organization repos listed

### ISSUE THREAD

**Issue by toddreed** [dennisreimann/ioctocat#437]
I just installed iOctocat and purchased the Pro upgrade. When I select "Organizations" under the "Repositories" section, none of the organizational repositories I have access to are listed (but the organizations are).

I can however access these repos from the "Watched" or "Starred" repos list, but this very inconvenient due to the large number of repos.

Why are the organization repos not listed?

**Comment by dennisreimann** [comment]
Do they appear once you refresh (pull down) the list? If not, please reauthenticate amd resstart the app, sorry for the trouble.

**Comment by toddreed** [comment]
Ah—refreshing worked. Thanks.

**Comment by dennisreimann** [comment]
Awesome, glad it worked for you. Thanks for the feedback!
