### ISSUE TITLE
Loading Error, NSURLErrorDomain error -1012

### ISSUE THREAD

**Issue by jrwagz** [dennisreimann/ioctocat#438]
Very often in the v2 app from the App Store I am getting this error when I try to get new data.  The error persists for what appears to be all requests until I re-enter my PW on the account screen and then login again.

Has anybody else experienced this problem?

**Comment by jrwagz** [comment]
I am just connecting to the standard GitHub, I am NOT using a GitHub enterprise server.

**Comment by dignifiedquire** [comment]
This is because github revoked their certificates yesterday because of the heartbleed issue.

**Comment by dignifiedquire** [comment]
See https://github.com/blog/1818-security-heartbleed-vulnerability and https://twitter.com/iOctocat/status/453601546639769600

**Comment by dennisreimann** [comment]
v2.3.5 has already been approved by Apple and will be available throughout the various App Stores today.

**Comment by jrwagz** [comment]
I thought it might be related to heartbleed, thanks for confirming, and thanks for the FANTASTIC app!
