### ISSUE TITLE
Unable to authenticate after new install (2FA)

### ISSUE THREAD

**Issue by mkb** [dennisreimann/ioctocat#440]
I am unable to authenticate my GitHub account using either a newly created application key or my normal password. Two-factor authentication is enabled on my account. How should I troubleshoot this?

**Comment by dennisreimann** [comment]
Hey, are you using the current App Store version?
Does your [GitHub Applications page](https://github.com/settings/applications) list any iOctocat tokens? You don't have to create them manually - if there are duplicates, please delete them.

**Comment by mkb** [comment]
Yes, I am using the most recent version of iOctocat with an up-to-date iOS. 

I did have multiple tokens listed for iOctocat on my various devices but deleted them all in the wake of the Heartbleed vulnerability. Because I use GitHub's two factor auth I would not expect my password to work in IOctocat by itself but I tried a few times anyway. Have you used iOctocat with GH two-factor-auth? What normally happens?

--mkb

**Comment by dennisreimann** [comment]
Okay, thanks for the clarifications :)

I'm using 2FA via SMS and it works fine. 
So what happens after you have entered your password? You should get a popup that asks you for the 2FA token - if you get yours via SMS too you should receive it within a few seconds. 

Or are you using an app for the 2FA token retrieval?

**Comment by mkb** [comment]
I am using SMS for 2FA as well. I have logged out of the GH web app and back in again a few times just to make sure I am using the correct password. As expected, I am prompted for a token which arrives on my phone in a few seconds. 

When I use that same password in iOctocat it simply says "Authentication failed".

Any thoughts on what to try next?

Thanks,

--mkb

**Comment by dennisreimann** [comment]
So you don't even get to the point where the 2FA token gets sent, because the initial login fails, right?
We had a case once where only reinstalling the app helped, see #429 - I don't know why this might happen, but can you try to delete the app, redownload it from the store and try again? Sorry for the hassle!

**Comment by mkb** [comment]
Yes, that's precisely it. 

I deleted iOctocat from my iPad and strangely the iPad version is not showing up for me in the App Store. I tried the iPhone version and authentication worked exactly as intended. Let's call this issue resolved and I'll keep checking on my own for the correct version to reappear on the flaky App Store. 

Thanks for your help!

--mkb

**Comment by dennisreimann** [comment]
Alright, glad it's working for you now!

v2 isn't universal yet, but the iPad support is what will ship next. I can't give an ETA for that, but I started to work on it already.

**Comment by mkb** [comment]
Excellent. Thanks again!

**Comment by gaelian** [comment]
I'm currently having this issue on iOS 8.0.2. I have two-factor auth enabled, just wondering if I could get some clarification on exactly what I'm supposed to be doing. Currently, I enter my login and password, submit and I immediately get an "Authentication failed" pop-up message. There is no option for me to enter any two-factor auth information.

I've tried deleting the app from my phone and re-installing the app as discussed here and in issue #492, but no change in outcome. I'm a little confused by the part in #492 where push notifications are mentioned, what do they have to do with anything? I can also see in my GitHub account's Security tab that each time I try to authenticate I'm generating a "user.two_factor_requested" event, if that means anything. iOctocat does not show up as needing to be updated, so I assume that means I'm on the latest released version.

Any assistance would be appreciated.

EDIT: I don't see any authorisation for iOctocat listed in my GitHub account.

**Comment by dennisreimann** [comment]
Hello Gaelian,

sorry I didn't reply earlier to this!

I just submitted a new version to Apple - please test again when v2.4.1 is available on the App Store.

Cheers,
Dennis

**Comment by mkb** [comment]
Will do. Thanks!

--mkb

**Comment by gaelian** [comment]
@dennisreimann OK will give that a go, thanks.
