### ISSUE TITLE
"Loading error" with Git Up app

### ISSUE THREAD

**Issue by bravokiloecho** [dennisreimann/ioctocat#442]
As of the last few weeks I haven't been able to view repositories with the Git Up app.

The list of repositories appears fine (and updates with the search filters) but when I navigate to an particular repository I get a red warning label that reads:

"Loading error. Could not load the requested resource."

This seems to be a fairly recent  issue as the app was working fine when I first installed it.

Any help would be great because this app is otherwise a really helpful tool.

**Comment by dennisreimann** [comment]
Yes, this is caused by GitHub changing their SSL certificates in response to the Heartbleed bug. I'll try to fix this soon, sorry for the inconvenience!

**Comment by bravokiloecho** [comment]
Understood! And thank you. Your work and the app is very much appreciated.

**Comment by dennisreimann** [comment]
I submitted a new version to Apple yesterday, I hope it will be available soon :)
