### ISSUE TITLE
Oauth key already exists when logging out and in again

### ISSUE THREAD

**Issue by stites** [dennisreimann/ioctocat#443]
This happened after the upgrade.

**Comment by dennisreimann** [comment]
Please go to your GitHub app settings (https://github.com/settings/applications), delete the iOctocat token and try to authenticate again.

**Comment by nilbus** [comment]
This workaround works. Please leave this issue open until ioctocat can resolve this properly on its own.

**Comment by wamatt** [comment]
This just happened to me after upgading. not ideal

**Comment by dennisreimann** [comment]
Should be fixed with v2.4.2 - please reopen if this still occurs :)

**Comment by wamatt** [comment]
:+1:
