### ISSUE TITLE
Authentication with just Application Key

### ISSUE THREAD

**Issue by jasonmit** [dennisreimann/ioctocat#445]
We use an internal authentication mechanism with github enterprise, so the oauth password it's requesting will not work.  For every other application I use to interface with GitHub Enterprise I use an Application key.  

How do I achieve this with Octocat?  With the Application key as my password I receive:

"Authenication failed" 
"Not found."

**Comment by dennisreimann** [comment]
Thanks for your feedback. I'll have to look into this as I haven't had this case before.

**Comment by shawndumas** [comment]
having a similar issue; corp github does not use passwords so I cannot get connected -- https://help.github.com/enterprise/2.0/user/articles/connecting-with-third-party-applications/

or even...
![image](https://cloud.githubusercontent.com/assets/56031/5493935/2987c0e6-86a4-11e4-8ace-b6c35c23838c.png)

**Comment by dennisreimann** [comment]
See #458
