### ISSUE TITLE
Git Up missing languages

### ISSUE THREAD

**Issue by texastoland** [dennisreimann/ioctocat#446]
I want to use Git Up to track Apple Swift libraries but it's not included in the language list. I guess they're not queryable. Maybe you could pull them from a repo to keep from having to publish updates?

PS I love your GitHub apps :boom:

**Comment by texastoland** [comment]
@dennisreimann Is this straightforward enough to update? Would it help to scrape the languages into CSV or something?

**Comment by dennisreimann** [comment]
I'll update it this month, have been very busy recently :)

**Comment by texastoland** [comment]
:ok_hand:

**Comment by dennisreimann** [comment]
@dnalot I just wanted to let you know that I submitted an update to the App Store with Swift included in the languages, as well as iPad and iPhone 6 (Plus) support :)

**Comment by texastoland** [comment]
:fireworks:
