### ISSUE TITLE
NSURLErrorDomain error 1012 on trying to login - Github Enterprise

### ISSUE THREAD

**Issue by bgriffith** [dennisreimann/ioctocat#447]
Hey,

Just downloaded the app for the first time and upgraded straight away to pro to allow for enterprise.

I can log-in with with public github creds, but when ever I try to log into an enterprise account I get the NSURLErrorDomain error (1012). I have two factor authentication on, but don't even get past the domain/username/password phase.

Any suggestions on what I can try? Never been able to login, so have nothing under github/settings/applications. Ps. SSL certificate isn't self-assigned.

**Comment by dennisreimann** [comment]
Hey Ben, thanks for your feedback. The problem seems to be SSL related - are you sure you aren't using a self-signed certificate on the other end?

**Comment by bgriffith** [comment]
Hey Dennis, sent you an email with further info, thanks for your help.

**Comment by dennisreimann** [comment]
Alright, I'll have a look :)
