### ISSUE TITLE
Scrolling Issue found in Git Up (+ feature request)

### ISSUE THREAD

**Issue by funky-monkey** [dennisreimann/ioctocat#450]
First off - Loving your Git Up app!
Second - Sorry to post it here - but i found no repo for your Git Up app. 
While scrolling in a selected repo, I want to scroll the full page - but there is a weird scrolling issue. Sometimes It only scrolls what is visible and not the full content page. The scroll just gets stuck.
This happens when tapping the repo header and then trying to scroll the content. The content scrolls underneath the header.

Also I'd like to propose a feature request; I'd like to share the repo i'm viewing with a UIActivityViewController (so the use can choose how to share)

For the rest - great app! (Every work break i have i check trending repos)
Thank you for making this :+1: 

![Scrolling issue](https://infinit.io/_/Sx5S8JL.png)

**Comment by dennisreimann** [comment]
Thanks for your feedback and letting me know about this issue. I'll take a look!

Also, thanks for the nice words about the app :)

**Comment by funky-monkey** [comment]
Welcome :-)
Does the 'bug report' make sense? If it does not just ask me and i can provide more information.

Best, 
Sidney
