### ISSUE TITLE
When viewing issues labels overlap 

### ISSUE THREAD

**Issue by bgriffith** [dennisreimann/ioctocat#452]
Labels of a certain length seem to overlap issue text.

![img_0007](https://cloud.githubusercontent.com/assets/2854338/10057599/fcef9b1e-6238-11e5-9afd-194c0d3f6769.jpg)

**Comment by dennisreimann** [comment]
Thanks for the bug report!

**Comment by bgriffith** [comment]
No problem :+1: - iPhone 5 btw.

**Comment by dennisreimann** [comment]
Yep, I can reproduce this :)

**Comment by dennisreimann** [comment]
Will be fixed in v2.8.2
