### ISSUE TITLE
No feedback for invalid account password entry

### ISSUE THREAD

**Issue by gregarious** [dennisreimann/ioctocat#454]
Upon entering an invalid password, there's no explicit prompt informing the user of the problem. The only visual feedback is a red bar dropping down quickly, and then 5 seconds later, flying back up. (The animation looks like a red navigation bar on a view controller being presented/dismissed). Here's a video demo: https://vid.me/hhBs.

I wasn't aware I was entering the wrong password for my account, so after multiple attempts, it just looked like the app's authentication flow was completely broken (especially given the spurious red bar animation).

Behavior seen on iPad 2, iOS 9.0.2.

**Comment by dennisreimann** [comment]
Alright, this looks pretty odd - thanks for reporting it!
