### ISSUE TITLE
Allow OAuth token access for GitHub Enterprise

### ISSUE THREAD

**Issue by docwhat** [dennisreimann/ioctocat#458]
With GitHub Enterprise, it would be nice to be able to pre-create the OAuth token(s) and have iOctocat use those pre-created token(s).

Some corporate policies don't allow for giving out the account password, even if just used to create the OAuth tokens.  In addition, the GitHub Enterprise may be configured to use an external authentication method (e.g. SASL, etc.).

It is more complicated, unfortunately, but it is better than nothing.

Example steps:
1. Create `iOctocat: Application` OAuth token with the permissions we're allowed to give applications.
2. Mail the token to our phone.
3. Copy the token.
4. Open iOctocat
5. Create a new Enterprise-with-OAuth token account
   1. Enter username
   2. Enter OAuth token
   3. Confirm

If I want push notification, then I would have to do similar steps but for the `iOctocat: Push Notifications` token.

**Comment by dennisreimann** [comment]
Thanks for your input, I'll consider this :)

**Comment by cabarria** [comment]
This is really needed or allowing personal access tokens. Most GHE implementations are going to use SSO/SAML. How can we get iOctocat to leverage one of these auth methods?

**Comment by SangHLee** [comment]
I agree with @docwhat and @cabarria's request for OAuth token access for GitHub Enterprise. @dennisreimann any update on this front? Thanks for your work!

**Comment by dennisreimann** [comment]
Thanks everyone for your feedback. I'm currently working on this and will update the app as soon as I'm finished with that :)

![bildschirmfoto 2016-10-07 um 12 22 45](https://cloud.githubusercontent.com/assets/886/19188832/c280ed34-8c94-11e6-9a95-59f30e3bd17f.png)

**Comment by cabarria** [comment]
Awesome!

Cesar Barria

**Comment by SangHLee** [comment]
@dennisreimann Thank you! :+1:
