### ISSUE TITLE
Getting errors when using personal token with GitHub Enterprise (with SSL certificate installed on iOS device)

### ISSUE THREAD

**Issue by SangHLee** [dennisreimann/ioctocat#459]
Hi,

I have installed SSL cert that is being used on my GitHub Enterprise domain on my iOS device per your FAQ suggestion. However, I can not still login to my GitHub Enterprise with my personal token. Any ideas?

Thanks for the great app!

**Comment by dennisreimann** [comment]
Thanks for your nice feedback :)

I'm sorry but for now you'll have to use the password as the app does not support personal access tokens yet.

**Comment by SangHLee** [comment]
My company is using Single Sign On (SSO) SAML via OneLogIn as the identity provider. This means, I can't just use my user name and password to log into my GitHub Enterprise account... Any chance of supporting personal access tokens? :smile: 

Thanks again. I used your app a lot, but ever since, SSO implementation with GitHub Enterprise, I can't access my repositories via iOctocat :disappointed:

**Comment by cabarria** [comment]
I'm experiencing the same issue. I wish it was clear in the app store that the app doesn't work with GitHub Enterprise SSO (SAML). Do you have an ETA for a fix?  Thxs

**Comment by dennisreimann** [comment]
See #458
