### ISSUE TITLE
Can't have my upgrade restored

### ISSUE THREAD

**Issue by ghost** [dennisreimann/ioctocat#460]
I had an upgrade of the app on my older phone but can't get it on the new phone. It doesn't do anything when I press the restore upgrade button

**Comment by dennisreimann** [comment]
Are you using the same Apple ID you bought the app/upgrade with?

Did you buy an upgrade for version 2 or are you talking about having bought version 1?

What message do you get when trying to restore?

**Comment by ghost** [comment]
I believe it was v2. And I used the same AppleID.

The message says 

```
Thank you and enjoy the upgrade 

Please re-authenticate your accounts ...
```

but if I try to add a new account, it takes me back to the upgrade page.

**Comment by dennisreimann** [comment]
The message confirms the successful restore :)

Do you see the state "Basic" or "Pro" when you pull the menu on the left all the way up? (below Settings)

Can you restart the app in case this still says "Free"?

**Comment by ghost** [comment]
It says basic. 2.7.1

I killed the app and launched it again, also restarted the whole phone. didn't do it.

**Comment by dennisreimann** [comment]
You need the Pro upgrade to use more than one account. That's the reason the upgrade view comes up when you try to add a new account.

**Comment by ghost** [comment]
yeah so that was the question. If I try to do the pro-upgrade, it seems like I have to pay again, even though I paid already.

**Comment by dennisreimann** [comment]
It looks like you originally upgraded to Basic as that's what you got restored. 

In case you want to upgrade to Pro now, you'd only have to pay the difference from Basic to Pro, not the full Pro price. I've set up a special tier for that upgrade path.

**Comment by ghost** [comment]
ah, I see. so basic is still a paid version. the name threw me off. thanks for the reply.

**Comment by dennisreimann** [comment]
Alright, glad I could help!
