### ISSUE TITLE
 "Loading error"

### ISSUE THREAD

**Issue by seya-zero2one** [dennisreimann/ioctocat#461]
When I try to access to files, several files return "Loading error" message which says the request resource could not be found.

This happens even for a simple file like a text based html file.  Is there a way to get around this problem?  I use 2.7.1 (Build 272 - pro) on my iPhone.

**Comment by seya-zero2one** [comment]
This is the message I'm talking anout.
![](http://i.imgur.com/Uawsz2q.jpg)

**Comment by koraktor** [comment]
Did you try to open the file on GitHub?

Do you have an example repository / file?

**Comment by seya-zero2one** [comment]
I created public samples which generate this error message.

For HTML files:
https://github.com/zero2onehub/testBox/tree/master/step8/presentation/VersionAprime/html
- helloWorld.html is OK.
- Step8.html generates this error message.

For PDF files:
https://github.com/zero2onehub/testBox/tree/master/step8/presentation/VersionAprime/pdf
- Test.pdf is OK
- step08_1.pdf generetes this error message.

I have no problem opening these file with the other iOS GitHub App, CodeHub.  I wonder what's wrong with iOctocat.

**Comment by seya-zero2one** [comment]
Is this error something to do with the file size ?  I have no issue to open them if I use PC.

**Comment by seya-zero2one** [comment]
Why is this case closed?  I prepared the samples which replicates the issue but no one followed this issue (I paid for this app and I asked for a help by submitting a problem statement via the app, but there was no support either).  It seems no one supports this app.  The development of this app is terminated?

**Comment by dennisreimann** [comment]
I closed the issue because I improved the error message for the next release.

The general problem in this case is, that the particular API returns blobs for up to 1MB and the files you mentioned are above that size limit. I'm not going to generally call another API that returns up to 100MB, because that might hurt users data plans. I might add an option to intentionally load large files in a future release.

**Comment by seya-zero2one** [comment]
Thank you very much for the clalification.  As long as the uses (including myself) understand the reason why we're getting the error that's fine.  The problem with this issue was that no one provided a clear explanation about this error for three moths.  Because of that, I thought this project is dead.  I'm glad that this project is still alive!

**Comment by dennisreimann** [comment]
No it isn't dead and I started to work on it more again. This is a side project and I try to bring in new features and bugfixes whenever I can find the time to do so.
