### ISSUE TITLE
can you close an issue from the app? I don't see a function

### ISSUE THREAD

**Issue by Jlowe63** [dennisreimann/ioctocat#468]

**Comment by Jlowe63** [comment]
Figured it out. It's under the email icon

**Comment by dennisreimann** [comment]
I just closed this issue via the app. On an issue view there is the actions button in the upper right corner. With the Basic upgrade this includes closing, editing, etc.

**Comment by Jlowe63** [comment]
One comment, when making a change to a label a message is displayed that is a saving message and while this is great it should drop when the user selects the next function such as using the action button where the saving message overlays the menu choices and blocks some text.
