### ISSUE TITLE
Storage usage

### ISSUE THREAD

**Issue by jrappen** [dennisreimann/ioctocat#471]
The App currently has 300 MB of "Documents & Data" listed via `Settings > General > Storage- & iCloud-Usage > Storage` on my iPhone.
I only found the ability to clear the avatar cache via the settings. I'd appreciate the ability to clear the whole cache.

**Comment by dennisreimann** [comment]
The app does not cache any data besides the avatars.

**Comment by jrappen** [comment]
Ok, follow up question. Where do the 300 MB come from?

**Comment by jrappen** [comment]
@dennisreimann ping
