### ISSUE TITLE
SSO (Single Sign On) is not supported

### ISSUE THREAD

**Issue by jdumanowski** [dennisreimann/ioctocat#474]
Team,

is there a way to use SSO with iOctocat? I am trying to access my companies private GitHub repo and I have purchased the 2 x 7€ add ons, but still can not get it to work. Please advice if this feature is available or comping soon, or how can I get a refund on the app. Thanks!

**Comment by jdumanowski** [comment]
Any chance to get an answer from the DEV Team? Or should I contact Apple for the refund?

**Comment by dennisreimann** [comment]
Sorry, that I did forget to answer your question!

In case you can log into your Enterprise instance from Safari it should also work in iOctocat. If that's not the case, the firewall or other settings of the instance prohibit the login and you should contact Apple for getting the purchase refunded. 

Sorry again! :)
