### ISSUE TITLE
iPhone X support!

### ISSUE THREAD

**Issue by urda** [dennisreimann/ioctocat#485]
This is a gorgeous app, and would look even better by supporting the iPhone X display.

**Comment by dennisreimann** [comment]
👍🏻

**Comment by Ru1x** [comment]
:+1:

**Comment by urda** [comment]
@dennisreimann congrats on the iPhone X update! I think this is a bug though (my poor face!):

![bug](https://user-images.githubusercontent.com/1648492/32824739-fbb3b326-c996-11e7-9fbb-ff697303475d.jpg)

**Comment by urda** [comment]
Also when I was fetching my version info, I noticed I can't scroll the left menu bar all the way down to see the full version string (notice the black bar on the bottom):

![bug](https://user-images.githubusercontent.com/1648492/32824842-6b1393d0-c997-11e7-946f-b9664b3e52ac.jpg)

Either way, love the look of it on the X's screen 🎉

**Comment by dennisreimann** [comment]
Alright, thanks for reporting this – I'll take a look!

**Comment by urda** [comment]
Thanks for the great app, can’t wait to see my face unstretched again! :)

**Comment by urda** [comment]
@dennisreimann Looking good!

![img_2559](https://user-images.githubusercontent.com/1648492/32985717-822d08ae-cc75-11e7-931b-0aaebd76bab1.jpg)

Finally, should the version number at the bottom be completely hidden, requiring a user to "pull up" on the left-hand menu?

**Comment by dennisreimann** [comment]
@urda I fixed that too, at least in the simulator it looked good to me. I don't have an iPhone X to test this with.

**Comment by iosdeveloper** [comment]
@dennisreimann @urda Can confirm the version footer looks fine on device.

**Comment by urda** [comment]
@dennisreimann @iosdeveloper This is how it looks to me on an iPhone X:

![Version GIF](https://user-images.githubusercontent.com/1648492/32993512-19ab8dd4-cd0e-11e7-932c-16b355345bbc.gif)

**Comment by dennisreimann** [comment]
@urda that's how it's supposed to be 😉

**Comment by urda** [comment]
@dennisreimann that’s what I figured (never paid attention to it before)! Figured I’d leave you a recording.

Thanks for this update! Looks so great on this screen.

**Comment by dennisreimann** [comment]
Thanks for the kind words!
