### ISSUE TITLE
iOS Push Notifications are not being received

### ISSUE THREAD

**Issue by whitfin** [dennisreimann/ioctocat#489]
Not entirely sure if this is bad setup or not, but the app definitely has Push enabled, and has created the appropriate tokens. However, I've had several notifications today and nothing has happened. 

Any ideas?

**Comment by dennisreimann** [comment]
The push notifications will be discontinued from this month on. I am sunsetting the app and will not be able to provide this service anymore.

**Comment by whitfin** [comment]
Hi @dennisreimann, fair enough :) when exactly do you plan on turning it off?

**Comment by dennisreimann** [comment]
I'll shut it down next week.
