### ISSUE TITLE
Problem running on the simulator.

### ISSUE THREAD

**Issue by nall** [dennisreimann/ioctocat#54]
I'm trying to run in the 3.1.2 simulator using Ad Hoc Distribution. It starts up, I see a blank table view and then I get the following. This is running with Xcode 3.2.2.

2010-01-28 16:34:35.744 iOctocat[39771:40b] **\* Terminating app due to uncaught exception 'NSInvalidUnarchiveOperationException', reason: '**\* -[NSKeyedUnarchiver decodeObjectForKey:]: cannot decode object of class (UITableViewCellContentView)'

This is with 1.0.9:  0d4ac2bcef7c6df6e0d83f5e30a584a1d9b11ca6

**Comment by nall** [comment]
I'm also getting this with 1.1.10: 65afa68ba2d8e2895f1286d575da6ae8081af5ff

**Comment by dennisreimann** [comment]
Why are you using the Ad Hoc Distribution for the simulator?

**Comment by nall** [comment]
It happens with Ad Hoc on the device too (my real goal) -- I just thought the simulator might be easier to reproduce on. 

I get the same results running Debug/Simulator-3.1.2 with the latest tree.

I guess this is just me? Weird.

**Comment by nall** [comment]
I get the same results on 3.0 and 3.1. Strangely, 3.2 works. I tried resetting my simulator but that didn't help.

**Comment by dennisreimann** [comment]
Does this still occur with the current version (1.2.0)?

**Comment by nall** [comment]
Nope. This looks to be gone now. Closing.

**Comment by dennisreimann** [comment]
nice, thank you for verifying.
