### ISSUE TITLE
Untitled

### ISSUE THREAD

**Issue by dima767** [dennisreimann/ioctocat#55]

**Comment by dima767** [comment]
Sorry, opened it by accident while playing with the latest iOctocat on my iPhone :-) Could safely be deleted.

**Comment by dennisreimann** [comment]
Did you add a new issue and send it with a blank title and text? In this case we should validate the form in the app...

**Comment by dima767** [comment]
Yes, sent it with blanks - by accident :-)

**Comment by dennisreimann** [comment]
Don't allow saving issues without title and text. Closed by c7c7c6d0a574e7535c81720d1faf2c1b84d0224d

**Comment by dennisreimann** [comment]
This is a test for posting comments with iOctocat :)

**Comment by dennisreimann** [comment]
Another test - posting comments seems to work :)
