### ISSUE TITLE
Create 'touch pull' gesture to page through feed entries (in addition to arrows on the navBar)

### ISSUE THREAD

**Issue by dima767** [dennisreimann/ioctocat#56]
Just like in Tweetie 2 :-)

http://www.youtube.com/watch?v=UjaXA1LBYNc (see around 6:15 mark)

**Comment by dennisreimann** [comment]
I have to think about that and I guess that would be difficult, because the webview that shows the content is scrollable...

**Comment by dima767** [comment]
I have no doubt that it's difficult, but I thought you'd be able to pull that off :-) I'm using a lot of iOctocat code as example for my own coding (I'm an iPhone coding newbie) :-)

I don't think there are any code examples how to do that kind of a thing anywhere on the web.

**Comment by klaustopher** [comment]
Hey, @dima767, there actially is: https://github.com/boctor/idev-recipes/tree/master/VerticalSwipeArticles

But erm ... Just realized the time of this post ... Nevermind, moving on ... :smile:
