### ISSUE TITLE
Move arrrows to bottom right

### ISSUE THREAD

**Issue by marlun** [dennisreimann/ioctocat#58]
I would prefer the arrows to be located in the bottom right since it is easier to reach and feels better. Just putting this up here so others can comment.

**Comment by dennisreimann** [comment]
Okay, what do other people think about that? It seems like placing that control in the top right corner has become a convention (Mail, Tweetie) - would you prefer them in the bottom right corner?

**Comment by dennisreimann** [comment]
okay, I'm closing this too as no one else seems to find this interesting and its against the known convention of having that menu in the upper right corner.
