### ISSUE TITLE
My Watchlist

### ISSUE THREAD

**Issue by dennisreimann** [dennisreimann/ioctocat#6]
It would be nice to have a list of watched repositories.

**Comment by dennisreimann** [comment]
This is currently not supported via the GitHub API

**Comment by intabulas** [comment]
adding comment for tracking purposes: we can add watch/unwatch actions but the api doesnt return a list of repo's being watched

**Comment by dennisreimann** [comment]
Until this is added to the GitHub API the watchlist is implemented locally...

**Comment by dennisreimann** [comment]
Added repository watchlist. Closed by 1eb94f39eddf77e71eb0cc7c3f4ea32a8cd8d56f
