### ISSUE TITLE
sort watched repositories based on activity

### ISSUE THREAD

**Issue by tadelv** [dennisreimann/ioctocat#60]
Is it possible to add sorting to the repositories view? I would like to see my watched repos sorted by activity just like on the github dashboard. 
Thanks!

**Comment by dennisreimann** [comment]
Currently the API doesn't support this

**Comment by darvin** [comment]
Maybe it is possible to implement without API request? Something like lazy sorting after view is loaded via multiply API calls? Will be that implementation accepted into main stream?

**Comment by tadelv** [comment]
Well you can always sort afterwards. I'll look it up and see what can be done.

**Comment by tadelv** [comment]
so, I have looked up the GitHub v3 api and it seems we can sort the repos via the updated_at attribute. easy as pie :)

**Comment by dennisreimann** [comment]
OKay, I'll tackle this later today :) thank you!

**Comment by tadelv** [comment]
Ha, I was on my way to fork the repo and do it myself. ok thanks, let me know how it works out or if you have any problems!

vid

**Comment by dennisreimann** [comment]
oh, didn't mean to take this away from you, go ahead if you like too, I'll merge it in. I thought about it and maybe it would be nice to have an option for how to sort the list, though I'm not sure about how to display that.

**Comment by dennisreimann** [comment]
Hmm, I can't seem to get this working with /user/watched?sort=pushed_at - did you achieve to get it done?

**Comment by tadelv** [comment]
So, finally got some time to get this done. I'll send you a pull request so you can review the changes.
