### ISSUE TITLE
Sometimes commits open in GitHub

### ISSUE THREAD

**Issue by koraktor** [dennisreimann/ioctocat#61]
When tapping on the commit SHA in the overview of a push, the new diff view doesn't show up. Instead the commit's GitHub page is opened. As far as I can tell this is pretty random.

**Comment by koraktor** [comment]
This seems to always reproduce the problem:
- Open a push with more than one commit
- Open the diff view of one of the commits
- Go back to the push overview
- Try to open another diff view
- This will cause the GitHub webpage to open (plus a long delay)

**Comment by dennisreimann** [comment]
Fixed 'Sometimes commits open in GitHub'. Closed by 647b0412771d4d198491633188dd3a9b4f93d603
