### ISSUE TITLE
remove my repos from watched list

### ISSUE THREAD

**Issue by jerodsanto** [dennisreimann/ioctocat#62]
The repositories view shows my repos and watched repos separately. It'd be nice if ioctocat removed all repos belonging to me from the watched list since they are already displayed above. 

Issue added from ioctocat. Love it :)

**Comment by dennisreimann** [comment]
Minor changes to jlavallee's commit. Filter user's repositories from the watched list. Closed by b3498964a60f09cab0d1e84f489caaac0ce38a8c.
