### ISSUE TITLE
Events: Collapse similar items

### ISSUE THREAD

**Issue by jk** [dennisreimann/ioctocat#63]
I got some people in my timeline which are doing heavy editjobs on their wiki pages, so my timeline gets unusable when they do. So it would be nice, if iOctocat can identify similar news items and collapse them.

![News Feed](http://web2.twitpic.com/img/66794227-067260213e4d4e2475196450586f211d.4b7c01c3-full.png)
Source: http://twitpic.com/13rmr7

**Comment by darvin** [comment]
I want to implement that feature will it be accepted in mainstream?

**Comment by dennisreimann** [comment]
@darvin go ahead, I'd pull it in.

**Comment by klaustopher** [comment]
Even on GitHub this is sort of annoying that there is no option to filter the news stream. Would love to see that in the App

**Comment by dennisreimann** [comment]
@darvin did you investigate about how to solve this?

**Comment by dennisreimann** [comment]
Wow, this one is three years old by now, but I'll tackle this when switching to the real event API. Right now we are using the events feed and it would be rather tedious to realize it with the current state.

**Comment by jk** [comment]
I'm looking forward to this, even after 3 years ;)

**Comment by dennisreimann** [comment]
fyi: The event API changes are done, I'll start working on this soon.

**Comment by dennisreimann** [comment]
Is this still relevant? If so, is there someone who would like to work on this?

**Comment by dennisreimann** [comment]
:bomb:
