### ISSUE TITLE
"Last Updated" pulldown should be updated

### ISSUE THREAD

**Issue by jridgewell** [dennisreimann/ioctocat#64]
When ever you open the app, the "Last updated" pulldown text should be upadated, also. Right now, the text is only updated when you manually pull the pulldown down.

Other than that, I love the feature.

**Comment by sukima** [comment]
How is this being calculated. I'm not seeing where it's getting this initial value. I'm wondering if the results are being cached in which case the delayed time displayed would be correct.

**Comment by jridgewell** [comment]
No, the feed itself is being updated each time the app is opened. ( I just opened it to check: I have results from 8 minutes ago while the "Last Updated" text says the feed was updated over an hour ago. )

I'll take a stab at figuring out where the value is stored.

**Comment by sukima** [comment]
So it looks like it is setting this value on load to the last time the application was launched. Is this the intended result? I'm curious why that was the design choice.

**Comment by jridgewell** [comment]
That is strange, the last updated variable has been set to this new time ( when the app starts ), but the pulldown still shows the old time.

Perhaps the updating function is being called to soon? ( I don't know Objective-C, so most everything in the source is a complete mystery to me. )
