### ISSUE TITLE
Crash in Networks / Forks

### ISSUE THREAD

**Issue by dennisreimann** [dennisreimann/ioctocat#66]
@tarasis reports:

iOctocat is crashing for me if I try & look at a projects Networks / Forks. First attempt shows this load error http://twitpic.com/1aidv4
the second attempt simply crashes the app. This was with previous version and the brand new release

**Comment by tarasis** [comment]
Will link crash reports next time I sync the iPhone, should be later one I find my data cable.

**Comment by dennisreimann** [comment]
Hmm, I can't verify it, please send me the crash report and I'll have a look at it :)

**Comment by tarasis** [comment]
As mentioned in the other issue I have reinstalled the app from the AppStore and now the list shows up correctly.

Here are the crash reports: http://files.me.com/tarasis/uyz4eu (link valid for 30 days)

**Comment by tucano** [comment]
same problem here: the app crash and exit when I try to load network in a repository

**Comment by dennisreimann** [comment]
which repository?

**Comment by tucano** [comment]
more details:
1. in a personal public repository: I click on network/forks, I see my user, I click on user and I see "loading repository" message. After that the application go back to Forks. 
2. Same in watched public repository.
3. In a private watched repository (not mine), when I click on network/forks the application crash

**Comment by dennisreimann** [comment]
Fix for crash in networks/forks. Closed by 78c2cff2e3c3203c817902c8e5ee62a0b9618841

**Comment by dennisreimann** [comment]
I was able to reproduce it thanks to tucanos report - the problem occured when the forks list was empty. I'll submit a new version for the App Store later today :)
