### ISSUE TITLE
Unable to Authenticate since entering Settings.app last night

### ISSUE THREAD

**Issue by tarasis** [dennisreimann/ioctocat#67]
Since finding the problem with the Network graph (issue 66), I am now unable to authenticate.

Basically once I found it was crashing with the Network Graph, I went searching for a version number. I went into Settings.App, didn't see one (I also didn't change anything) and went back to iOctocat and it failed to authenticate.

Thinking it might be a githut issue I waited to this morning and tried again but it still wouldn't authenticate. I then tried setting the Key and Username again from inside the App but to no avail. It still fails: http://twitpic.com/1al3bz

**Comment by dennisreimann** [comment]
Hey Robert, does this still happen? I can't verify it...

**Comment by dennisreimann** [comment]
Okay, I'll habe an eye on this, but for now I close this issue.
