### ISSUE TITLE
Some special characters eat up spaces

### ISSUE THREAD

**Issue by koraktor** [dennisreimann/ioctocat#69]
Some special characters like double quotes `"` and `<` eat up spaces (sometimes before them, sometimes after them, sometimes both).

Examples:
koraktor/steam-condenser@564f3a4850a82ad1c20327c52639a666695a9a85
koraktor/steam-condenser#37

Edit: Sorry, GitHub Markdown seems to be buggy too. ;) These should be links:

http://github.com/koraktor/steam-condenser/commit/564f3a4850a82ad1c20327c52639a666695a9a85
http://github.com/koraktor/steam-condenser/issues#issue/37

**Comment by dennisreimann** [comment]
At least http://github.com/koraktor/steam-condenser/issues#issue/37 seems to work for me now. Please reopen this issue with a current example if the problem still occurs.

**Comment by koraktor** [comment]
Seems to be fixed. Thanks.
