### ISSUE TITLE
Add the ability to browse issues

### ISSUE THREAD

**Issue by dima767** [dennisreimann/ioctocat#7]
If project exposes issues, display them.

**Comment by intabulas** [comment]
issue integration is implemented in my fork. A pull request has already been sent

**Comment by dennisreimann** [comment]
thanks to intabulas a basic version of this is implemented (and integrated into the master)

**Comment by dennisreimann** [comment]
Browsing issues is now integrated, but I guess we will polish the edges some more. For now, this issue can be seen as closed.
