### ISSUE TITLE
feedControl segmented control doesn't resize automatically

### ISSUE THREAD

**Issue by jessearmand** [dennisreimann/ioctocat#71]
I have to add this in viewDidLoad to fit the title for each of the segmented control item:
<code>[feedControl sizeToFit];</code>

**Comment by dennisreimann** [comment]
When and where doesn't the item resize properly? Do you have a screenshot for that?

**Comment by jessearmand** [comment]
It's on MyFeedsController.m. The segmented control on the navigation bar of the "Feeds" tab item. The titles are "News Feed" and "My Activity".

It wasn't like this before, but I did a rebuild with the latest version on the master branch. I installed, and there's the problem. So, I have to add the line above to viewDidLoad.

Sorry, I can't provide you a screenshot for now, just imagine that the segmented control has a very small width.

**Comment by dennisreimann** [comment]
Hmm, I can't reproduce it, which version of the SDK are you building with? For me 3.0 works fine :)

**Comment by jessearmand** [comment]
I'm using iPhone OS 3.2 as a base SDK, and targeting iPhone OS 3.0 at minimum. I installed this on iPhone OS 3.1.2. It could be something with the base SDK and target combination.

**Comment by dennisreimann** [comment]
Does this still occur with the current version (1.2.0)?

**Comment by jessearmand** [comment]
Not anymore in iOS 4.

**Comment by dennisreimann** [comment]
okay, thank you for verifying that :)
