### ISSUE TITLE
"Watch" from the iPhone app didn't work

### ISSUE THREAD

**Issue by stuffmc** [dennisreimann/ioctocat#75]
I just watched a Repo from the iPhone and
- It's not reflected on github
- It says this repo has "0 followers"

(this was tweetstream)

**Comment by dennisreimann** [comment]
Does this still occur with the current version (1.2.0)?

**Comment by stuffmc** [comment]
Nope :( Just pulled and reinstalled on my iPhone. It's even worse than what I had seen: If you watch a repo from the app it doesn't reflect on github, and if you unwatch on github it still says "unwatch" on the iPhone. 

:( So the watch feature is pretty broken/useless in the app.

**Comment by dennisreimann** [comment]
Okay, this seems to be an API bug that was recently introduced, see:
http://support.github.com/discussions/api/65-userfollowuser-not-working

**Comment by dennisreimann** [comment]
I just verified it and at least in the current version watching repositories works fine for me, I started watching tweetstream just now and unwatched it afterwards.

**Comment by dennisreimann** [comment]
Refactored watching and following. Closed by cffcad8c6014c142375676cceaae5e928370c845
