### ISSUE TITLE
*Request* Native iPad resolution 

### ISSUE THREAD

**Issue by johntdyer** [dennisreimann/ioctocat#76]
It would be great to have a properly formatted version for the iPad, just a suggestion =)

John

**Comment by dima767** [comment]
I second that! Either the separate app or refactor it to be a universal app with all the iPad UI goodies :-)

**Comment by AngryAnt** [comment]
No separate app. Please do it riiite ;)

**Comment by dennisreimann** [comment]
This might happen, stay tuned ;)

**Comment by dennisreimann** [comment]
I'm currently working on an universal version of the app. Check out the iPad Branch for a preview :)

**Comment by dennisreimann** [comment]
This is done now and will be available on the App Store soon.
