### ISSUE TITLE
View code natively

### ISSUE THREAD

**Issue by justincampbell** [dennisreimann/ioctocat#78]
Would like to be able to view files/code natively in the app with the option to open in browser

**Comment by dima767** [comment]
+1

**Comment by schorsch** [comment]
+1

**Comment by dennisreimann** [comment]
I'll look at that once the universal version has been approved by Apple.

**Comment by jmeosbn** [comment]
+1 this is the only reason I keep two github apps on my device.

**Comment by MJGraf** [comment]
This would really be a great enhancement

**Comment by dennisreimann** [comment]
@MJGraf Can you give me your use case for that? I'm just asking because I've never felt the need to browse repos or code files on the iPhone or iPad, but maybe it's just me. I'd like to know what people would use it for, so that I get a better understanding of what needs to be implemented.

I'm definitely willing to make this happen, as you aren't the only one asking for that feature.

**Comment by MJGraf** [comment]
Hallo Dennis,

(ich hoffe mal, auf Deutsch ist ok...). Ich bin in meiner Freizeit begeisterter MediaPortal-Nutzer. In meiner beruflichen Vergangenheit hab ich auch mal programmiert. Deswegen versuche ich - so gut das geht - bei der neuen MediaPortal 2-Version mitzuhelfen. Da meine Programmierkenntnisse aber mittlerweile viel zu schlecht geworden sind, um dort als Programmierer mitzuhelfen, versuche ich hauptsächlich, die Nutzer und Programmierer von MediaPortal 1 von den Vorteilen von MediaPortal 2 zu überzeugen. Besonders für das Überzeugen der Programmierer brauche ich aber einen Überblick über das Konzept von Mediaportal 2. Deswegen kommt es durchaus vor, dass ich mir zu einem bestimmten Bereich einfach den (wirklich verdammt gut dokumentierten) Code anschaue - Soweit, dass ich dann das Konzept der Programmierung verstehe, reichen meine Programmierkenntnisse noch.

So viel zur Vorrede. Das technische Problem ist jetzt, dass die Website von GitHub sich recht schwergängig aufbaut und auch wenn ich in Deiner App über den eingebauten Browser durch den Code scrolle, geht das ziemlich ruckelig. Davon abgesehen, ist es auf dem IPad auch kein Vergnügen, die ziemlich kleinen Links anzuklicken, um durch das Repository zu browsen. Schöner wäre es, wenn man das ohne Aufbauverzögerung und ohne Ruckler beim Scrollen native machen könnte. Ich hab dazu bis vor Kurzem den Git Viewer Light benutzt - aber der geht seit ca. 2 Wochen nicht mehr ("Server Data Error", schon wenn ich versuche, nach einem Repository zu suchen - hat sich da was an der Github-Website geändert?).

Nun ist Deine App insgesamt viel schöner und hat mehr Funktionen, aber Native Code Browsing wäre natürlich das Sahnhäubchen... Davon abgesehen: wenn ich mir den Diff eines Commits ansehe, geht das doch schon per eingebautem Viewer? Kann man den nicht mit recht wenig Aufwand so verändern, dass man auch durch das Repository browsen kann und dann darin die ganzen Code-Files ansehen kann?

Davon abgesehen aber vielen Dank für die App - wirklich klasse!

**Comment by jmeosbn** [comment]
I'd like to support MJGraf's answer, but since I have no idea what he said (except that it involves the MediaPortal project) then I guess he doesn't want any help in getting this feature implemented.

The obvious use case is being on the iOS device when discovering a new dev, repo or code change etc. and wanting to view it rightaway rather than when you get back to your desktop - by which time you've probably forgot about it.  This happens quite often if you have a jailbroken device as devs frequently link from Cydia to source in github.  Also when reading dev blogs etc.

**Comment by justincampbell** [comment]
I frequently like to read source code on my phone, and opening a
browser and viewing the raw text in Safari is not the best experience.

-Justin

Sent from my iPhone

On Jun 19, 2012, at 3:19 PM, jmeosbn
reply@reply.github.com
wrote:

**Comment by MJGraf** [comment]
Sorry guys, I didn't know that this email has so many (non-german) readers.

Basically I said that I used to be a programmer long time ago and today I'm trying to support the MediaPortal project (in particular MediaPortal 2) as far as my time permits. However, my experience as a programmer was long time ago and so I'm no real coder. What I'm trying to do, however, is convince people over there of the advantages of Mediaportal 2 over Mediaportal 1 (although I love MP1 as well...). That means that I sometimes would just like to read some code of MP2 to be able to understand the concept and the structure of MP2. (without understanding everything in detail, but on a level that enables me to write a very small plugin and write something about it in the forum.

Therefore, I do not really sit for hours in front of my laptop to do real coding. I would just like to flip though some of the source code to get a general understanding of the structure - and that can be easily done with an IPad and a glass of wine...

Cheers,
Michael

**Comment by jmeosbn** [comment]
Thanks Michael,

I think this is a similar use case to my own (and many others I'd think).  It's nice to review code at times when you're not actually set up _to code_.

As Justin has said, reviewing code via Safari is not ideal - on the iPhone it's damn near impossible!

**Comment by dennisreimann** [comment]
k, I'll do this. At first, I'll try to find something that would be more suited to display codefiles then just putting them into an UIWebView like we are doing it right now with the diffs. Any recommendations for that?

**Comment by jmeosbn** [comment]
A lot of apps seem to be using content editable web views, like mail and sparrow etc., but that'd require doing own syntax highlighting etc. 

You could look at something like:https://github.com/peterhajas/Genesis

Just using the basic diff in ioctocat is easier than in Safari (although it essentially looks the same). The option to set width/font size and syntax highlighting (of actual source) would help a lot though. 

Regards,

Jamie Osborne
