### ISSUE TITLE
'you have no private repositories' while i do have those

### ISSUE THREAD

**Issue by mediamedics** [dennisreimann/ioctocat#79]
hi, 

I really like ioctocat for my iphone to keep track of my github account. However since the last update I can't view my private repositories anymore. I have 5 private repositories, which I can access using the  github website. I removed my account name and api token in the settings of the app and closed the app for real (using the iOS multitask bar) Restarted and logged in again with my github account credentials. But still no private repositories on my repositories tab. I do see my public ones and watched ones. This feature did work before, I have used it many times to check commits from my team-members.

I hope this can be easily solved, thanks

Victor

**Comment by dennisreimann** [comment]
Hey, thanks for mentioning this - which version are you using? 1.2.0 or 1.2.1?

**Comment by mediamedics** [comment]
hi, I can't find the version in the app itself, I just bought it in the app store some time ago and thought I mentioned this issue here. I own it for a few months and by latest update I mean the version which was pushed to the app store after the iOS release. (If there are more of those, then I probably have the last one, because I always update quickly.). Another thing I notice is the following (hope this helps): I have feeds in the Feeds tab of my own activity in private repositories and of collaborators as well. When I try to view those items and click on the links which would point to a repository this will work. I can see the title of the private repository in the navbar of the feeds window for example, but when I then click on the 'issues' table cell I get an alert window with the following error "Loading error, Could not load the issues". When I try to load a commit from a collaborator from within the news feed it will open the commit view with the hash title, but the rest of the view has no data to show, only the 'Loading commit...'  default message. I hope this helps, if you have any suggestions to what i could try please reply

**Comment by dennisreimann** [comment]
You can see the version number in iTunes, v1.2.1 came out yesterday and is supposed to fix an authentication error I introduced in v1.2.0 which leads to the loading errors you are describing.

**Comment by mediamedics** [comment]
aha, nice to know, The version I have is 1.2.1, date modified 25-07-10, fairplay version 2, on iPhone 3GS, iOS 4.0.1

**Comment by st3f** [comment]
I'm having the same problem... My private Repos aren't shown anymore. I'm using an iPhone 3GS, iOS 4.0.1 and ioctocat 1.2.1...

**Comment by dennisreimann** [comment]
Okay, this seems to be a GitHub issue, because as far as I can see everything should work fine in iOctocat (at least we're doing it like the docs state it: http://develop.github.com/p/repo.html)

Can you please verify that your private repos are not show here (you must be authenticated):

https://github.com/api/v2/xml/repos/show/YOUR_LOGIN

And with explicit HTTP Basic Auth:

https://YOUR_LOGIN:YOUR_TOKEN@github.com/api/v2/xml/repos/show/YOUR_LOGIN

If your private repos don't appear there, I'll open a discussion in the API support forums (http://support.github.com/discussions/api).

**Comment by st3f** [comment]
None of my private repos is listed, with or withour Auth... Thx

**Comment by mediamedics** [comment]
Thanks for your investigation. I can indeed verify that on both api locations you provided I only get an xml response with public repositories. So I think you are right about the GitHub side of this issue. Please open the discussion on the api support forums, (I am not yet familiar with the github api).

**Comment by dennisreimann** [comment]
Okay, Rick pushed a fix for the API, see: http://support.github.com/discussions/api/57-reposshowlogin-is-missing-private-repositories

I committed the adapted authentication for iOctocat, can someone verify that it works now? http://github.com/dbloete/ioctocat/commit/3355010be5a20f126e3a2e1691145e321bf8dea9

**Comment by dennisreimann** [comment]
Whaa, I commited something wrong yesterday (though it seemed to work too), can someone verify that the current version shows the private repositories?

**Comment by mediamedics** [comment]
I am confirming that this issue is now solved after I downloading the update from the appstore. all private repos have returned in the app and work correctly! thx

**Comment by dennisreimann** [comment]
Thank you!
