### ISSUE TITLE
Add the ability to enter authentication details via application

### ISSUE THREAD

**Issue by dima767** [dennisreimann/ioctocat#8]
Not only via 'Settings' application. The first time application is opened and the 'Root View Controller' tries call the REST API, check the user defaults and if there is no username/api token set, present a view to enter them. Then save 'em in the NSUserDefaults and go on...

P.S.

I'm just starting out with iPhone development, so if I'm way off, please disregard :-)

**Comment by dennisreimann** [comment]
Perfectly valid request :)

**Comment by dennisreimann** [comment]
It's closed, but maybe it can be refactored someday.

**Comment by dennisreimann** [comment]
Added the ability to enter authentication details via application. Closed by 6e13cbfe5d3fb6ed6e7d1b02d28f9edd7b77bc47

**Comment by dennisreimann** [comment]
test
