### ISSUE TITLE
Opening "githubauth" URL doesn't fill or login, only UIAlert...

### ISSUE THREAD

**Issue by stuffmc** [dennisreimann/ioctocat#80]
I opened the githubauth:// url, it displayed a UIAlert telling me the credentials, but the boxes where not filled and I wasn't logged, so it makes no sense.

**Comment by dennisreimann** [comment]
Fix for setting credentials after opening githubath URL. Closed by 2a8e7d5eccb135be1cddd030ff816d9a46d7ca6c
