### ISSUE TITLE
Commit details load on second try

### ISSUE THREAD

**Issue by koraktor** [dennisreimann/ioctocat#81]
If you tap on a commit ID it should bring you to the details of that commit, e.g. author, message and changed files. For me, this only works if I try it once, than go back and try it for the second time. The first try will always result in an infinite "Loading..." throbber.

**Comment by dennisreimann** [comment]
Fixed loading flow for commit. Closed by c0640c6420988940ea6f8d2e7b4fd713492d8e3e
