### ISSUE TITLE
Organizations: View organizations feed

### ISSUE THREAD

**Issue by nealenssle** [dennisreimann/ioctocat#85]
It would be great to take advantage somehow of the new "Organizations" feature on GitHub, and be able to switch contexts.

**Comment by dennisreimann** [comment]
Unfortunately the API doesn't support organizations, yet… we'll have to wait.

**Comment by eskatos** [comment]
Is there a github issue about organizations support in api for which we can vote and watch ?

**Comment by dennisreimann** [comment]
I think they won't work on the version 2 of the API anymore, because tehre's at least planning for a new version, which I hope will include organizations and inbox.

**Comment by eskatos** [comment]
github published the documentation about organizations api some days ago: https://github.com/blog/758-new-organizations-api

**Comment by mikebranski** [comment]
I realize the Organizations API was just published last month, but I just wanted to echo support for this feature. Really looking forward to it being implemented!

**Comment by dennisreimann** [comment]
Which features would you like to see implemented with the organizations API?

**Comment by eskatos** [comment]
Consuming the feeds of organizations you are member of is the main feature I would like to see implemented.

Following the actual ioctocat structure I could see this feature as merging organizations feeds with the main "News" feed and add a "Organization" section in the app to see a ProfileView? per Organization. But to do that you'll have to merge the "Repositories" and "Profile" view I think. Of course this is only wishes, that's up to you :)

**Comment by mikebranski** [comment]
Seeing organization repositories under the Repositories view would be really nice!

**Comment by dennisreimann** [comment]
Hmm, unfortunately the organizations API doesn't seem to work ATM:

https://github.com/api/v2/json/organizations/dbloete
https://github.com/api/v2/json/organizations/repositories

I'll integrate this as soon as it works again.

**Comment by rcoup** [comment]
Seems like its working ok:

https://github.com/api/v2/json/organizations/dbloete doesn't work (presumably there's no dbloete org), but https://github.com/api/v2/json/user/show/dbloete/organizations does, and the https://github.com/api/v2/json/organizations/repositories API works if you authenticate.

**Comment by dennisreimann** [comment]
Ok, that was my fault… I'll try to integrate the Organizations API as soon as I'll find the time for it, which won't be in the next four weeks :(

**Comment by dennisreimann** [comment]
I'll take this up next - had a couple of refactorings I had to do first, but they are done now :)

**Comment by eskatos** [comment]
Awesome :-)

**Comment by dennisreimann** [comment]
Okay, this is done now - please test it. I'll do an App Store build the next days…
