### ISSUE TITLE
quick access to this project

### ISSUE THREAD

**Issue by schorsch** [dennisreimann/ioctocat#86]
Add btn. To easy Jump to this repo or its issues

**Comment by dennisreimann** [comment]
Could you explain this a bit further?

**Comment by schorsch** [comment]
I wanted to quickly create an issue for ioctocat, but had to search a long way until i finally reached this project to report something.
So somewhere in the settings a quicklink "report issue" or "go to ioctocat" would be nice

**Comment by dennisreimann** [comment]
Okay, I'll try to add this the next time I work on the app :)
