### ISSUE TITLE
GHResource loading fails

### ISSUE THREAD

**Issue by weakfl** [dennisreimann/ioctocat#88]
iOctocat[1577:707](0018fcd0.0096)-[GHResource loadingFinished:] JSON parsing failed: Error Domain=CJSONScannerErrorDomain Code=-1 "Could not scan dictionary. Dictionary that does not start with '{' character." UserInfo=0x1d6fc0 {NSLocalizedDescription=Could not scan dictionary. Dictionary that does not start with '{' character.}

**Comment by dennisreimann** [comment]
When does this error occur? Which resource is getting loaded or which view are you on?

**Comment by weakfl** [comment]
When the app starts. Seems to be either while loading the private feed or right after it.
The end tag of the feed is in the log right before the error:

< /feed>

2011-03-16 18:41:31.902 iOctocat[1577:707](0018fcd0.0096)-[GHResource loadingFinished:] ...

**Comment by dennisreimann** [comment]
Closed by 71ec85ab8ae22c4019ad9ee9178c7ab9661d9e16.
