### ISSUE TITLE
Commit Diffs

### ISSUE THREAD

**Issue by JakeWharton** [dennisreimann/ioctocat#9]
This is one of the most common things I do when browsing GitHub from my phone. It would be so nice to be able to do this from within the app. The line numbers can probably be omitted, just the red/green/white colorings would be awesome.

**Comment by dennisreimann** [comment]
Oh, I could not imagine someone is really doing this... ;)

**Comment by JakeWharton** [comment]
I know it's a very tall order. The best I can do is make mock-ups and write pseudo-Objective-C code if it will help.

**Comment by intabulas** [comment]
so I poked around at this a bit and the api exists but the rendering is the fun part..  Curious if  Three20's new style system might make this easier vs using say a heavily customized table cell.. but after 1.0 for sure

**Comment by dennisreimann** [comment]
I recently added that :)
