### ISSUE TITLE
Crashes when tapping gear icon on commits

### ISSUE THREAD

**Issue by mikebranski** [dennisreimann/ioctocat#91]
1. Go to Repositories
2. Select any repository
3. Select a branch
4. Select a commit
5. Tap the settings (gear/cog) icon

The app crashes for me every time. I'm using a version built from source from right after the organizations integration was added, so this may be an issue on my end, but I wanted  to report it in case others are experiencing it as well.

**Comment by lglenn** [comment]
I am able to reproduce this -- iOS 4.3 on an iPhone 4.

**Comment by dennisreimann** [comment]
Fix for crashes when tapping gear icon on commits. Closed by a2c77cf1faf0d0c0c63c3c8d0304de11c8c9d84a.
