### ISSUE TITLE
Crashes on 3G 3.1.3

### ISSUE THREAD

**Issue by pschichtel** [dennisreimann/ioctocat#98]
Versions 1.3.0 and 1.3.1 of iOctocat crash shortly after launching. Sometime it crashes on the first touch or swipe, but mostly it crashes a second or two after launch.

Device: iPhone 3G
iOS: 3.1.3

**Comment by dennisreimann** [comment]
Can you deliver some more information on this, maybe send in a crash report?It might be, that the app requires an iOS version newer than 3.1.3, I'll investigate.

**Comment by pschichtel** [comment]
where can I find the crash reports?
I use jailbroken iOS 3.1.3, because iOS4+ runs way too slow.

**Comment by manuszep** [comment]
Hi,

I also experience crashes on startup. I just downloaded the app on a non-jailbroken Ipod touch v 4.3.3
As soon as I entered the API key and username, it crashed and then every time I try to relaunch. Apparently when the app logs-on and tries to pull feeds.

**Comment by pschichtel** [comment]
I got the some problem on my new iPhone 3GS with jailbroken 4.3.3 today. Yesterday it worked without problems.

**Comment by koraktor** [comment]
@manuszep @quickwango

That problem is unrelated to this issue. It has been fixed by #103 and should (hopefully) arrive in the App Store shortly.

**Comment by dennisreimann** [comment]
@koraktor is correct. The crashes that are occuring since yesterday are related to GitHub API changes, see https://convore.com/github/github-event-json-feed-problems/ for details on that.

The current master version is already fixed and a new version is on it's way to Apple, but I don't know how long it will take them to accept it.

**Comment by dennisreimann** [comment]
Please reopen this issue with a more detailed description if the problem still occurs with the current master.

**Comment by gmazel** [comment]
Uh oh! iOctocat crashes upon 1st launch w no message on my iTouch w iOS 3.1.3... Just downloaded it this morning.
I have 1.1 GB available.

**Comment by dennisreimann** [comment]
Can you submit/upload the crash report? See this link for details on how to do that:  http://www.pixelloopgames.com/main/support/submit-crash-logs

**Comment by gmazel** [comment]
Thanks Dennis,
The app seems to be working now. It may have been a connection issue at the hotel I was staying in.
Gregg
